### ISSUE TITLE
BUG: plotting model events not connecting/disconnecting as required

### ISSUE THREAD

**Issue by to266** [hyperspy/hyperspy#1207]
to preproduce:
```python
In [1]: import numpy as np

In [2]: import hyperspy.api as hs

In [3]: s = hs.signals.Signal1D(np.arange(50).reshape(5,10))

In [4]: m = s.create_model()

In [5]: m.append(hs.model.components1D.Gaussian())

In [6]: m.append(hs.model.components1D.Gaussian())

In [7]: %matplotlib
Using matplotlib backend: Qt4Agg

In [8]: m.plot()
```

Then move the navigator, and this comes up:
```python
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: Unnamed 0th axis, trait: index, old value: 1, new value: 2
Traceback (most recent call last):
  File "/home/to266/dev/hyperspy/hyperspy/model.py", line 511, in update_plot
    self._update_model_line()
AttributeError: 'Model1D' object has no attribute '_update_model_line'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/to266/anaconda3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/home/to266/anaconda3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/home/to266/dev/hyperspy/hyperspy/axes.py", line 820, in _on_index_changed
    self.events.indices_changed.trigger(obj=self)
  File "<string>", line 4, in trigger
  File "/home/to266/dev/hyperspy/hyperspy/events.py", line 397, in trigger
    function(**{kw: kwargs.get(kw, None) for kw in kwsl})
  File "/home/to266/dev/hyperspy/hyperspy/model.py", line 718, in fetch_stored_values
    component.fetch_stored_values(only_fixed=only_fixed)
  File "/home/to266/anaconda3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/to266/dev/hyperspy/hyperspy/model.py", line 549, in suspend_update
    self.update_plot()
  File "/home/to266/dev/hyperspy/hyperspy/model.py", line 516, in update_plot
    self._disconnect_parameters2update_plot(components=self)
  File "/home/to266/dev/hyperspy/hyperspy/model.py", line 492, in _disconnect_parameters2update_plot
    component.events.active_changed.disconnect(self._model_line.update)
  File "/home/to266/dev/hyperspy/hyperspy/events.py", line 368, in disconnect
    (function, self))
ValueError: The <bound method Signal1DLine.update of <hyperspy.drawing.signal1d.Signal1DLine object at 0x7f232a4eed30>> function is not connected to <hyperspy.events.Event: Event that triggers when the `Component.active` changes.: set()>.
ERROR:traits:Exception occurred in traits notification handler for object: Unnamed 0th axis, trait: index, old value: 1, new value: 2
Traceback (most recent call last):
  File "/home/to266/dev/hyperspy/hyperspy/model.py", line 511, in update_plot
    self._update_model_line()
AttributeError: 'Model1D' object has no attribute '_update_model_line'
```

**Comment by to266** [comment]
apparently @dnjohnstone already encountered this, and the problem is that [this](https://github.com/hyperspy/hyperspy/blob/master/hyperspy/model.py#L554) line is supposed to read `_update_model_line`

**Comment by francisco-dlp** [comment]
#1208
