### ISSUE TITLE
Error when saving HDF5 after BSS

### ISSUE THREAD

**Issue by andyroo101** [hyperspy/hyperspy#1344]
After performing BSS on an EELS spectrum and then trying to save as an HDF5 format the following error is reported:

ERROR:hyperspy.io_plugins.hdf5:The hdf5 writer could not write the following information in the file: bss_node : FastICA(algorithm='parallel', fun='logcosh', fun_args=None, max_iter=200,
    n_components=None, random_state=None, tol=1e-10, w_init=None,
    whiten=False)
Traceback (most recent call last):
  File "C:\Users\Andy\Anaconda3\lib\site-packages\hyperspy\io_plugins\hdf5.py", line 439, in dict2hdfgroup
    group.attrs[key] = value
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (C:\Minonda\conda-bld\h5py_1474482825505\work\h5py\_objects.c:2705)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (C:\Minonda\conda-bld\h5py_1474482825505\work\h5py\_objects.c:2663)
  File "C:\Users\Andy\Anaconda3\lib\site-packages\h5py\_hl\attrs.py", line 93, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "C:\Users\Andy\Anaconda3\lib\site-packages\h5py\_hl\attrs.py", line 169, in create
    htype = h5t.py_create(original_dtype, logical=True)
  File "h5py\h5t.pyx", line 1450, in h5py.h5t.py_create (C:\Minonda\conda-bld\h5py_1474482825505\work\h5py\h5t.c:16099)
  File "h5py\h5t.pyx", line 1470, in h5py.h5t.py_create (C:\Minonda\conda-bld\h5py_1474482825505\work\h5py\h5t.c:15933)
  File "h5py\h5t.pyx", line 1525, in h5py.h5t.py_create (C:\Minonda\conda-bld\h5py_1474482825505\work\h5py\h5t.c:15834)
TypeError: Object dtype dtype('O') has no native HDF5 equivalent

Reproduce using:
s = load("someDataFile")
s.decomposition(True)
s.blind_source_separation(4)
s.save("newFile.hdf5")

**Comment by francisco-dlp** [comment]
Thanks for reporting the issue.

Even though the error looks scary, it actually saves the file properly, at least in my case. The scaryness of the error is certainly an issue. Could you confirm that it also saves the file properly in you case?

**Comment by thomasaarholt** [comment]
Can confirm, on behalf of @andyroo101. Saves correctly. Any thoughts on fixing it?

**Comment by francisco-dlp** [comment]
#1378
