### ISSUE TITLE
ROI error for latest version of numpy

### ISSUE THREAD

**Issue by bm424** [hyperspy/hyperspy#1411]
The latest version version of numpy ([release notes here](https://github.com/numpy/numpy/releases)) has deprecated indexing using floats to index arrays, which has broken ROIs, resulting in the following (for example) traceback:

```python-traceback
Traceback (most recent call last):
  File "/home/bm424/Documents/phd/dev/test/venv/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-1876e2251fb7>", line 1, in <module>
    roi(dat)
  File "/home/bm424/Documents/phd/dev/test/venv/lib/python3.5/site-packages/hyperspy/roi.py", line 1138, in __call__
    order=order)
  File "/home/bm424/Documents/phd/dev/test/venv/lib/python3.5/site-packages/hyperspy/roi.py", line 1074, in profile_line
    linewidth=linewidth)
  File "/home/bm424/Documents/phd/dev/test/venv/lib/python3.5/site-packages/hyperspy/roi.py", line 998, in _line_profile_coordinates
    data[0, :, :] = np.tile(line_col, [linewidth, 1]).T
  File "/home/bm424/Documents/phd/dev/test/venv/lib/python3.5/site-packages/numpy/lib/shape_base.py", line 881, in tile
    return c.reshape(shape_out)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
```

Steps to reproduce:

1. Clean virtual environment (Python 3.5)
2. `pip install hyperspy`
3. In IPython shell:
    ```python
    import hyperspy.api as hs
    import numpy as np
    dat = hs.signals.Signal2D(np.random.rand(20, 20, 40, 40))
    roi = hs.roi.Line2DROI(5, 5, 15, 15, 4)
    roi(dat)  # Raises exception.
    ```

This can currently be overcome by downgrading numpy to version 1.11

**Comment by sem-geologist** [comment]
does it works so only with np.dtype = float64?
