### ISSUE TITLE
Add support for plotting float16?

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1417]
Using ROI with certain dtypes throws an exception:

```Python
import hyperspy.api as hs
import numpy as np
s = hs.signals.Signal2D(np.random.random(size=(100,100)))
line_roi = hs.roi.Line2DROI(1., 1., 50., 50., 1)
s.plot()
roi1D = line_roi.interactive(s, color="yellow") # This works

s = hs.signals.Signal2D(np.random.random(size=(100,100)).astype('float16'))
line_roi = hs.roi.Line2DROI(1., 1., 50., 50., 1)
s.plot()
roi1D = line_roi.interactive(s, color="yellow") # This throws an exception, but adds the line roi
```

The exception: https://gist.github.com/magnunor/bb66dafad715e225a4292693e9beb2db

**Comment by francisco-dlp** [comment]
This is a bug if we should support this operation on float16 data. However, should we? If not, we could simply document it.

Are there more dtypes "affected"?

**Comment by ericpre** [comment]
Actually, this is plotting float16 which is not supported and matplotlib doesn't support it:

```python
import matplotlib.pyplot as plt
import numpy as np

data = np.random.random(size=(100,100)).astype('float16')
plt.imshow(data)
```
output:
```
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 519, in _draw_idle
    self.draw()
  File "/opt/miniconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)
  File "/opt/miniconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)
  File "/opt/miniconda3/lib/python3.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/miniconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2628, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/opt/miniconda3/lib/python3.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/miniconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/matplotlib/image.py", line 584, in draw
    renderer, renderer.get_image_magnification())
  File "/opt/miniconda3/lib/python3.7/site-packages/matplotlib/image.py", line 831, in make_image
    unsampled=unsampled)
  File "/opt/miniconda3/lib/python3.7/site-packages/matplotlib/image.py", line 429, in _make_image
    self.get_filterrad())
ValueError: Unsupported dtype
```

**Comment by francisco-dlp** [comment]
I suggest closing it then.

**Comment by ericpre** [comment]
Documented in #2202.
