### ISSUE TITLE
test_compilers.obj is installed in the wrong directory

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1575]
When I install hyperspy from Rnm I get an install error, as it can't find test_compilers.obj. If my hyperspy path is:
`C:\Users\thomasaar\Downloads\hyperspy\`
Then it is installed in 
`C:\Users\thomasaar\Downloads\hyperspy\Users\thomasaar\Downloads\hyperspy\hyperspy\misc\etc`
It is easily spotted by the creation of a "Users" folder in the hyperspy directory.

This appears to only be an issue on Windows?

**Comment by thomasaarholt** [comment]
The error I got from installing was:
```
PS C:\Users\thomasaar\Downloads\hyperspy> pip install -e ./
Obtaining file:///C:/Users/thomasaar/Downloads/hyperspy
    Complete output from command python setup.py egg_info:
    test_compilers.c
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\thomasaar\Downloads\hyperspy\setup.py", line 294, in <module>
        with update_version_when_dev() as version:
      File "C:\Users\thomasaar\Downloads\hyperspy\setup.py", line 272, in __enter__
        stdout=subprocess.PIPE)
      File "C:\ProgramData\Miniconda3\lib\subprocess.py", line 676, in __init__
        restore_signals, start_new_session)
      File "C:\ProgramData\Miniconda3\lib\subprocess.py", line 955, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\thomasaar\Downloads\hyperspy\`
```
Note that the lines in setup.py may have changed since.
