### ISSUE TITLE
hs.interactive() does not behave the same depending if it is called in a cell or the next in Jupyter

### ISSUE THREAD

**Issue by kociak** [hyperspy/hyperspy#1688]
Hi
Not quite sure this is a bug as I am fairly unconfident in what I am doing.
If I run the following code:

```
%matplotlib qt5
%config IPCompleter.greedy = True

import hyperspy.api as hs
import numpy as np
import hyperspy as hyperspy

ss=hs.signals.Signal1D(np.random.random((100,100,1000)))
ss.plot()

rec = hs.roi.RectangularROI(left=10, right=30, top=10, bottom=20)
rectangle_ROI = rec.interactive(ss,color='red')
mean_rectangle_ROI = hs.interactive(rectangle_ROI.sum,\
                                      event=rectangle_ROI.axes_manager.events.any_axis_changed,\
                                      recompute_out_event=None)
def generate_data(axes_manager=None):
    return mean_rectangle_ROI.data

lolo=hyperspy.drawing.signal1d.Signal1DLine()
lolo.line_properties={'type':'line'}
lolo.data_function=generate_data

f=hyperspy.drawing.signal1d.Signal1DFigure()
f.axes_manager=ss.axes_manager
f.axis=ss.axes_manager.signal_axes[0]# not sure I am confortable with that...
f.add_line(lolo)
lolo.plot()#don't plot f!!! this will generate and error!
#split here
hs.interactive(f=lolo.update,\
                                      event=rectangle_ROI.axes_manager.events.any_axis_changed)
```
I have a different behaviour whether I put all the code in the same cell, or if the last line is put separately in another.
If I put the code in the same cell, `hs.interactive` generates an error (see below the traceback).
if I put the code in the next cell, it generates a warning as soon as the event is triggered, i.e when I move the ROI (see below the traceback).
I am pretty sure I made something wrong, as the error sound to be due to an error of initialization of an `axis` somewhere, but can't put the finger on it... Thanks!

Error traceback (one cell):

```
TypeError                                 Traceback (most recent call last)
<ipython-input-1-048693d594ea> in <module>()
     24 f.add_line(lolo)
     25 lolo.plot()#don't plot f!!! this will generate and error!
---> 26 hs.interactive(f=lolo.update,                                      event=rectangle_ROI.axes_manager.events.any_axis_changed)

/anaconda/lib/python3.6/site-packages/hyperspy/interactive.py in interactive(f, event, recompute_out_event, *args, **kwargs)
    125 
    126 def interactive(f, event="auto", recompute_out_event="auto", *args, **kwargs):
--> 127     cls = Interactive(f, event, recompute_out_event, *args, **kwargs)
    128     return cls.out
    129 

/anaconda/lib/python3.6/site-packages/hyperspy/interactive.py in __init__(self, f, event, recompute_out_event, *args, **kwargs)
     79             self.out = self.kwargs.pop('out')
     80         else:
---> 81             self.out = self.f(*self.args, **self.kwargs)
     82         try:
     83             fargs = list(inspect.signature(self.f).parameters.keys())

/anaconda/lib/python3.6/site-packages/hyperspy/drawing/signal1d.py in update(self, force_replot)
    350             self.text.set_text(self.axes_manager.indices)
    351         if self.ax.figure.canvas.supports_blit:
--> 352             self.ax.hspy_fig._draw_animated()
    353         else:
    354             self.ax.figure.canvas.draw_idle()

/anaconda/lib/python3.6/site-packages/hyperspy/drawing/figure.py in _draw_animated(self)
     37             canvas = self.ax.figure.canvas
     38             if canvas.supports_blit:
---> 39                 canvas.restore_region(self._background)
     40             for ax in self.figure.axes:
     41                 artists = []

/anaconda/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py in restore_region(self, region, bbox, xy)
    449     def restore_region(self, region, bbox=None, xy=None):
    450         renderer = self.get_renderer()
--> 451         return renderer.restore_region(region, bbox, xy)
    452 
    453     def draw(self):

/anaconda/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py in restore_region(self, region, bbox, xy)
    357 
    358         else:
--> 359             self._renderer.restore_region(region)
    360 
    361     def start_filter(self):

TypeError: restore_region() argument 1 must be matplotlib.backends._backend_agg.BufferRegion, not None

```

Warning traceback (splitted cells):
```

Jupyter Notebook
Untitled38 Last Checkpoint: 6 minutes ago (autosaved) [Python 3]

Python 3

    File
    Edit
    View
    Insert
    Cell
    Kernel
    Widgets
    Help

%matplotlib qt5

%config IPCompleter.greedy = True

​

import hyperspy.api as hs

import numpy as np

import hyperspy as hyperspy

​

ss=hs.signals.Signal1D(np.random.random((100,100,1000)))

ss.plot()

​

rec = hs.roi.RectangularROI(left=10, right=30, top=10, bottom=20)

rectangle_ROI = rec.interactive(ss,color='red')

mean_rectangle_ROI = hs.interactive(rectangle_ROI.sum,\

                                      event=rectangle_ROI.axes_manager.events.any_axis_changed,\

                                      recompute_out_event=None)

def generate_data(axes_manager=None):

    return mean_rectangle_ROI.data

​

lolo=hyperspy.drawing.signal1d.Signal1DLine()

lolo.line_properties={'type':'line'}

lolo.data_function=generate_data

​

f=hyperspy.drawing.signal1d.Signal1DFigure()

f.axes_manager=ss.axes_manager

f.axis=ss.axes_manager.signal_axes[0]# not sure I am confortable with that...

f.add_line(lolo)

lolo.plot()#don't plot f!!! this will generate and error!

hs.interactive(f=lolo.update,\

                                      event=rectangle_ROI.axes_manager.events.any_axis_changed)

Exception occurred in traits notification handler for object: Unnamed 1st axis, trait: size, old value: 10, new value: 100
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/anaconda/lib/python3.6/site-packages/hyperspy/axes.py", line 817, in _on_size_changed
    self.events.any_axis_changed.trigger(obj=self)
  File "<string>", line 4, in trigger
  File "/anaconda/lib/python3.6/site-packages/hyperspy/events.py", line 402, in trigger
    function(**{kw: kwargs.get(kw, None) for kw in kwsl})
  File "/anaconda/lib/python3.6/site-packages/hyperspy/interactive.py", line 111, in recompute_out
    if out.data.shape == self.out.data.shape:
AttributeError: 'NoneType' object has no attribute 'data'
ERROR:traits:Exception occurred in traits notification handler for object: Unnamed 1st axis, trait: size, old value: 10, new value: 100
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/anaconda/lib/python3.6/site-packages/hyperspy/axes.py", line 817, in _on_size_changed
    self.events.any_axis_changed.trigger(obj=self)
  File "<string>", line 4, in trigger
  File "/anaconda/lib/python3.6/site-packages/hyperspy/events.py", line 402, in trigger
    function(**{kw: kwargs.get(kw, None) for kw in kwsl})
  File "/anaconda/lib/python3.6/site-packages/hyperspy/interactive.py", line 111, in recompute_out
    if out.data.shape == self.out.data.shape:
AttributeError: 'NoneType' object has no attribute 'data'
Exception occurred in traits notification handler for object: Unnamed 1st axis, trait: offset, old value: 10.0, new value: 12.0
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/anaconda/lib/python3.6/site-packages/hyperspy/axes.py", line 823, in _on_offset_changed
    self.events.any_axis_changed.trigger(obj=self)
  File "<string>", line 4, in trigger
  File "/anaconda/lib/python3.6/site-packages/hyperspy/events.py", line 402, in trigger
    function(**{kw: kwargs.get(kw, None) for kw in kwsl})
  File "/anaconda/lib/python3.6/site-packages/hyperspy/interactive.py", line 111, in recompute_out
    if out.data.shape == self.out.data.shape:
AttributeError: 'NoneType' object has no attribute 'data'
ERROR:traits:Exception occurred in traits notification handler for object: Unnamed 1st axis, trait: offset, old value: 10.0, new value: 12.0
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/anaconda/lib/python3.6/site-packages/hyperspy/axes.py", line 823, in _on_offset_changed
    self.events.any_axis_changed.trigger(obj=self)
  File "<string>", line 4, in trigger
  File "/anaconda/lib/python3.6/site-packages/hyperspy/events.py", line 402, in trigger
    function(**{kw: kwargs.get(kw, None) for kw in kwsl})
  File "/anaconda/lib/python3.6/site-packages/hyperspy/interactive.py", line 111, in recompute_out
    if out.data.shape == self.out.data.shape:
AttributeError: 'NoneType' object has no attribute 'data'

Exception occurred in traits notification handler.
Please check the log file for details.

Exception occurred in traits notification handler for object: Unnamed 1st axis, trait: offset, old value: 12.0, new value: 17.0
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/anaconda/lib/python3.6/site-packages/hyperspy/axes.py", line 823, in _on_offset_changed
    self.events.any_axis_changed.trigger(obj=self)
  File "<string>", line 4, in trigger
  File "/anaconda/lib/python3.6/site-packages/hyperspy/events.py", line 402, in trigger
    function(**{kw: kwargs.get(kw, None) for kw in kwsl})
  File "/anaconda/lib/python3.6/site-packages/hyperspy/interactive.py", line 111, in recompute_out
    if out.data.shape == self.out.data.shape:
AttributeError: 'NoneType' object has no attribute 'data'
ERROR:traits:Exception occurred in traits notification handler for object: Unnamed 1st axis, trait: offset, old value: 12.0, new value: 17.0
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/anaconda/lib/python3.6/site-packages/hyperspy/axes.py", line 823, in _on_offset_changed
    self.events.any_axis_changed.trigger(obj=self)
  File "<string>", line 4, in trigger
  File "/anaconda/lib/python3.6/site-packages/hyperspy/events.py", line 402, in trigger
    function(**{kw: kwargs.get(kw, None) for kw in kwsl})
  File "/anaconda/lib/python3.6/site-packages/hyperspy/interactive.py", line 111, in recompute_out
    if out.data.shape == self.out.data.shape:
AttributeError: 'NoneType' object has no attribute 'data'
Exception occurred in traits notification handler for object: Unnamed 1st axis, trait: offset, old value: 17.0, new value: 18.0
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/anaconda/lib/python3.6/site-packages/hyperspy/axes.py", line 823, in _on_offset_changed
    self.events.any_axis_changed.trigger(obj=self)
  File "<string>", line 4, in trigger
  File "/anaconda/lib/python3.6/site-packages/hyperspy/events.py", line 402, in trigger
    function(**{kw: kwargs.get(kw, None) for kw in kwsl})
  File "/anaconda/lib/python3.6/site-packages/hyperspy/interactive.py", line 111, in recompute_out
    if out.data.shape == self.out.data.shape:
AttributeError: 'NoneType' object has no attribute 'data'
ERROR:traits:Exception occurred in traits notification handler for object: Unnamed 1st axis, trait: offset, old value: 17.0, new value: 18.0
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/anaconda/lib/python3.6/site-packages/hyperspy/axes.py", line 823, in _on_offset_changed
    self.events.any_axis_changed.trigger(obj=self)
  File "<string>", line 4, in trigger
  File "/anaconda/lib/python3.6/site-packages/hyperspy/events.py", line 402, in trigger
    function(**{kw: kwargs.get(kw, None) for kw in kwsl})
  File "/anaconda/lib/python3.6/site-packages/hyperspy/interactive.py", line 111, in recompute_out
    if out.data.shape == self.out.data.shape:
AttributeError: 'NoneType' object has no attribute 'data'
Exception occurred in traits notification handler for object: Unnamed 1st axis, trait: offset, old value: 18.0, new value: 20.0
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/anaconda/lib/python3.6/site-packages/hyperspy/axes.py", line 823, in _on_offset_changed
    self.events.any_axis_changed.trigger(obj=self)
  File "<string>", line 4, in trigger
  File "/anaconda/lib/python3.6/site-packages/hyperspy/events.py", line 402, in trigger
    function(**{kw: kwargs.get(kw, None) for kw in kwsl})
  File "/anaconda/lib/python3.6/site-packages/hyperspy/interactive.py", line 111, in recompute_out
    if out.data.shape == self.out.data.shape:
AttributeError: 'NoneType' object has no attribute 'data'
ERROR:traits:Exception occurred in traits notification handler for object: Unnamed 1st axis, trait: offset, old value: 18.0, new value: 20.0
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/anaconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/anaconda/lib/python3.6/site-packages/hyperspy/axes.py", line 823, in _on_offset_changed
    self.events.any_axis_changed.trigger(obj=self)
  File "<string>", line 4, in trigger
  File "/anaconda/lib/python3.6/site-packages/hyperspy/events.py", line 402, in trigger
    function(**{kw: kwargs.get(kw, None) for kw in kwsl})
  File "/anaconda/lib/python3.6/site-packages/hyperspy/interactive.py", line 111, in recompute_out
    if out.data.shape == self.out.data.shape:
AttributeError: 'NoneType' object has no attribute 'data'

```

**Comment by ericpre** [comment]
I have polished a bit #1674 and you may be interested to give a try at it. If so, please give me a feedback! :)

When I was working on #1674, I had a error very similar to yours but I can't remember exactly what, sorry... but I think I was doing something wrong. Not familiar enough with the interactivity part to tell more.
It looks to me that the different behaviour that you observed, whether you put all the code in the same cell or not may be misleading, can the notebook add a layer of complexity? In python or ipython qtconsole, it does not work neither.

**Comment by kociak** [comment]
thanks! I had a look to your PR. I have to admit I am new with the git/github way of working and have no idea how to test it....

**Comment by francisco-dlp** [comment]
@kociak, @to266 has reccommended [GitKranken](https://www.gitkraken.com/) to some people around who are new to git and they seem to like it.

**Comment by ericpre** [comment]
@kociak, are you aware of the [dev guide](http://hyperspy.org/hyperspy-doc/current/dev_guide.html)? If not, it means, that it does not have enough visibility... 
There is also this [pdf document](https://github.com/hyperspy/hyperspy-demos/blob/master/Github_tutorial_IMC_2014.pdf) about the github workflow. It may look a bit confusing at the first look but this is a good graphical overview of the workflow.

**Comment by kociak** [comment]
gosh, no... thks @ericpre ! I'll read it!

**Comment by francisco-dlp** [comment]
@kociak, I think that the issue is that ``interactive`` wasn't the best fit for the job in this case. The following slightly modified script works for me:

```python

%matplotlib qt5
%config IPCompleter.greedy = True

import hyperspy.api as hs
import numpy as np
import hyperspy as hyperspy

ss=hs.signals.Signal1D(np.random.random((100,100,1000)))
ss.plot()

rec = hs.roi.RectangularROI(left=10, right=30, top=10, bottom=20)
rectangle_ROI = rec.interactive(ss,color='red')
mean_rectangle_ROI = hs.interactive(rectangle_ROI.sum,
                                    event=rectangle_ROI.axes_manager.events.any_axis_changed,
                                    recompute_out_event=None)

lolo=hyperspy.drawing.signal1d.Signal1DLine()
lolo.line_properties={'type':'line'}
lolo.data_function=lambda axes_manager: mean_rectangle_ROI.data

f=hyperspy.drawing.signal1d.Signal1DFigure()
f.axes_manager=ss.axes_manager
f.axis=ss.axes_manager.signal_axes[0]# not sure I am confortable with that...
f.add_line(lolo)
lolo.plot()#don't plot f!!! this will generate and error!

mean_rectangle_ROI.events.data_changed.connect(lolo.update, kwargs=[])

```

**Comment by kociak** [comment]
@francisco-dlp Simple and elegant (also thanks for the lambda version of `data_function`). Just work for me as well. I apparently got confused between `events` and `interactive`. I'll keep working on improving my use of `Signal1dLine`and if this works, I'll probably understand better as well `events` and try to give an example in the doc on `Roi` events trigerring different actions.
Thanks also @ericpre.

**Comment by francisco-dlp** [comment]
Thanks @kociak for the feedback and for reporting the issues here.
