### ISSUE TITLE
Install dev version on windows

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy#1704]
@k8macarthur reported the following issue in gitter:

```
Obtaining file:///C:/Users/macark/Documents/GitHub/hyperspy
    Complete output from command python setup.py egg_info:
    C:\Users\macark\Documents\GitHub\hyperspy\setup.py:180: UserWarning: WARNING: C compiler can't be found.
    Only slow pure python alternative functions will be available.
    To use fast implementation of some functions writen in cython/c either:
    a) check that you have compiler (EXACTLY SAME as your python
    distribution was compiled with) installed,
    b) use binary distribution of hyperspy (i.e. wheels, egg, (only osx and win)).
    Installation will continue in 5 sec...
      Installation will continue in 5 sec...""")
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\macark\Documents\GitHub\hyperspy\setup.py", line 298, in <module>
        with update_version_when_dev() as version:
      File "C:\Users\macark\Documents\GitHub\hyperspy\setup.py", line 275, in __enter__
        stdout=subprocess.PIPE)
      File "c:\program files\anaconda3\lib\subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "c:\program files\anaconda3\lib\subprocess.py", line 1224, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\macark\Documents\GitHub\hyperspy\
```

I could reproduce the installation error in an anaconda distribution on Windows 64 bits. Note that there is first the warning related to the compilation of the Cpython part and then the actual error.

Adding `shell=True` as an argument of subprocess.Popen in [setup.py#L275](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/setup.py#L275) seems to be a way to fix... However, I am not sure if this is the proper way.

**Comment by ericpre** [comment]
Fixed in #1723.
