### ISSUE TITLE
Logging Error when applying ICA analysis

### ISSUE THREAD

**Issue by wodebc** [hyperspy/hyperspy#1745]
Hi
I installed Hyperspy Winpython Buddle v1.3.0 already. When I used the ICA analysis through the 'Console' window, the Logging Error came out. Could someone help me? Thanks a lot!. Below is the error info:

cs.change_dtype('float')
cs.decomposition()

--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\logging\__init__.py", line 982, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\hspy_scripts\..\python-3.5.1\Scripts\hyperspyui.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\hyperspyui\__main__.py", line 132, in main
    app.exec_()
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\console_widget.py", line 411, in eventFilter
    return self._event_filter_console_keypress(event)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\frontend_widget.py", line 381, in _event_filter_console_keypress
    return super(FrontendWidget, self)._event_filter_console_keypress(event)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\console_widget.py", line 1166, in _event_filter_console_keypress
    self.execute(interactive = not shift_down)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\history_console_widget.py", line 47, in execute
    source, hidden, interactive)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\console_widget.py", line 630, in execute
    self._execute(source, hidden)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\hyperspyui\widgets\consolewidget.py", line 75, in _execute
    msg_id = self.kernel_client.execute(source, hidden)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\inprocess\client.py", line 102, in execute
    self._dispatch_to_kernel(msg)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\inprocess\client.py", line 170, in _dispatch_to_kernel
    kernel.dispatch_shell(stream, msg_parts)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\inprocess\ipkernel.py", line 80, in execute_request
    super(InProcessKernel, self).execute_request(stream, ident, parent)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\interactiveshell.py", line 2683, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\interactiveshell.py", line 2793, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\interactiveshell.py", line 2847, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-82b69c9f3ca2>", line 1, in <module>
    cs.decomposition()
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\hyperspy\_signals\eds_tem.py", line 527, in decomposition
    navigation_mask=navigation_mask, *args, **kwargs)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\hyperspy\learn\mva.py", line 212, in decomposition
    signal_mask=signal_mask,)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\hyperspy\learn\mva.py", line 1162, in normalize_poissonian_noise
    "Scaling the data to normalize the (presumably)"
Message: 'Scaling the data to normalize the (presumably) Poissonian noise'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\logging\__init__.py", line 982, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\hspy_scripts\..\python-3.5.1\Scripts\hyperspyui.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\hyperspyui\__main__.py", line 132, in main
    app.exec_()
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\console_widget.py", line 411, in eventFilter
    return self._event_filter_console_keypress(event)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\frontend_widget.py", line 381, in _event_filter_console_keypress
    return super(FrontendWidget, self)._event_filter_console_keypress(event)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\console_widget.py", line 1166, in _event_filter_console_keypress
    self.execute(interactive = not shift_down)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\history_console_widget.py", line 47, in execute
    source, hidden, interactive)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\console_widget.py", line 630, in execute
    self._execute(source, hidden)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\hyperspyui\widgets\consolewidget.py", line 75, in _execute
    msg_id = self.kernel_client.execute(source, hidden)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\inprocess\client.py", line 102, in execute
    self._dispatch_to_kernel(msg)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\inprocess\client.py", line 170, in _dispatch_to_kernel
    kernel.dispatch_shell(stream, msg_parts)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\inprocess\ipkernel.py", line 80, in execute_request
    super(InProcessKernel, self).execute_request(stream, ident, parent)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\interactiveshell.py", line 2683, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\interactiveshell.py", line 2793, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\interactiveshell.py", line 2847, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-82b69c9f3ca2>", line 1, in <module>
    cs.decomposition()
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\hyperspy\_signals\eds_tem.py", line 527, in decomposition
    navigation_mask=navigation_mask, *args, **kwargs)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\hyperspy\learn\mva.py", line 213, in decomposition
    _logger.info('Performing decomposition analysis')
Message: 'Performing decomposition analysis'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\logging\__init__.py", line 982, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\hspy_scripts\..\python-3.5.1\Scripts\hyperspyui.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\hyperspyui\__main__.py", line 132, in main
    app.exec_()
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\console_widget.py", line 411, in eventFilter
    return self._event_filter_console_keypress(event)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\frontend_widget.py", line 381, in _event_filter_console_keypress
    return super(FrontendWidget, self)._event_filter_console_keypress(event)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\console_widget.py", line 1166, in _event_filter_console_keypress
    self.execute(interactive = not shift_down)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\history_console_widget.py", line 47, in execute
    source, hidden, interactive)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\console_widget.py", line 630, in execute
    self._execute(source, hidden)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\hyperspyui\widgets\consolewidget.py", line 75, in _execute
    msg_id = self.kernel_client.execute(source, hidden)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\inprocess\client.py", line 102, in execute
    self._dispatch_to_kernel(msg)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\inprocess\client.py", line 170, in _dispatch_to_kernel
    kernel.dispatch_shell(stream, msg_parts)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\inprocess\ipkernel.py", line 80, in execute_request
    super(InProcessKernel, self).execute_request(stream, ident, parent)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\interactiveshell.py", line 2683, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\interactiveshell.py", line 2793, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\interactiveshell.py", line 2847, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-82b69c9f3ca2>", line 1, in <module>
    cs.decomposition()
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\hyperspy\_signals\eds_tem.py", line 527, in decomposition
    navigation_mask=navigation_mask, *args, **kwargs)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\hyperspy\learn\mva.py", line 466, in decomposition
    self.undo_treatments()
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\hyperspy\learn\mva.py", line 1203, in undo_treatments
    _logger.info("Undoing data pre-treatments")
Message: 'Undoing data pre-treatments'
Arguments: ()

**Comment by thomasaarholt** [comment]
This is unusual. What sort of dataset are you applying ICA to? If you just call `cs` to see the signal shape, how large is it?

Could you format the code and error between sets of three of these symbols, ```, as described in the [formatting guide](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code)?
Then it looks like this:
```python
cs.change_dtype(float)
cs.decomposition()
```

**Comment by francisco-dlp** [comment]
The error doesn't seem to be related to HyperSpy itself but to the ``logging`` standard library. This is strange as nobody else seems to be affected by this bug. We've used the bundle extensively e.g. for training, and we've never seen this issue. Could it be an installation issue? Maybe another program has modified the files? By the way, are you using 32-bits or the 64-bit version?

**Comment by wodebc** [comment]
Hi,
Below is the code. The dataset is core_shell.hdf5, simply from the tutorial. I can do ICA with this dataset using the window interface but this doesn't work for the code in the "console " window. I used the win 32-bits version.

`import hyperspy.api as hs

cs=hs.load('c:\Downloads\core_shell.hdf5')

cs.change_dtype(float)

cs.decomposition()

--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\interactiveshell.py", line 2847, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-cb6bc4849875>", line 1, in <module>
    c.decomposition()
NameError: name 'c' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\interactiveshell.py", line 1795, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'NameError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\interactiveshell.py", line 2793, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\interactiveshell.py", line 2864, in run_code
    self.showtraceback()
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\interactiveshell.py", line 1798, in showtraceback
    value, tb, tb_offset=tb_offset)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\ultratb.py", line 1373, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\ultratb.py", line 1281, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\ultratb.py", line 1130, in structured_traceback
    tb_offset)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\ultratb.py", line 1067, in format_exception_as_a_whole
    head = self.prepare_header(etype, self.long_header)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\ultratb.py", line 1020, in prepare_header
    width = min(75, get_terminal_size()[0])
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\utils\terminal.py", line 116, in get_terminal_size
    return _get_terminal_size((defaultx, defaulty))
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\shutil.py", line 1071, in get_terminal_size
    size = os.get_terminal_size(sys.__stdout__.fileno())
AttributeError: 'NoneType' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\interactiveshell.py", line 1795, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AttributeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\inprocess\ipkernel.py", line 80, in execute_request
    super(InProcessKernel, self).execute_request(stream, ident, parent)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\interactiveshell.py", line 2683, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\interactiveshell.py", line 2812, in run_ast_nodes
    self.showtraceback()
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\interactiveshell.py", line 1798, in showtraceback
    value, tb, tb_offset=tb_offset)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\ultratb.py", line 1373, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\ultratb.py", line 1281, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\ultratb.py", line 1130, in structured_traceback
    tb_offset)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\ultratb.py", line 1067, in format_exception_as_a_whole
    head = self.prepare_header(etype, self.long_header)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\core\ultratb.py", line 1020, in prepare_header
    width = min(75, get_terminal_size()[0])
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\IPython\utils\terminal.py", line 116, in get_terminal_size
    return _get_terminal_size((defaultx, defaulty))
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\shutil.py", line 1071, in get_terminal_size
    size = os.get_terminal_size(sys.__stdout__.fileno())
AttributeError: 'NoneType' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\logging\__init__.py", line 982, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\hspy_scripts\..\python-3.5.1\Scripts\hyperspyui.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\hyperspyui\__main__.py", line 132, in main
    app.exec_()
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\console_widget.py", line 411, in eventFilter
    return self._event_filter_console_keypress(event)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\frontend_widget.py", line 381, in _event_filter_console_keypress
    return super(FrontendWidget, self)._event_filter_console_keypress(event)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\console_widget.py", line 1166, in _event_filter_console_keypress
    self.execute(interactive = not shift_down)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\history_console_widget.py", line 47, in execute
    source, hidden, interactive)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\console_widget.py", line 630, in execute
    self._execute(source, hidden)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\hyperspyui\widgets\consolewidget.py", line 75, in _execute
    msg_id = self.kernel_client.execute(source, hidden)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\inprocess\client.py", line 102, in execute
    self._dispatch_to_kernel(msg)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\inprocess\client.py", line 170, in _dispatch_to_kernel
    kernel.dispatch_shell(stream, msg_parts)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\kernelbase.py", line 237, in dispatch_shell
    self.log.error("Exception in message handler:", exc_info=True)
Message: 'Exception in message handler:'
Arguments: ()
Traceback (most recent call last):
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\console_widget.py", line 411, in eventFilter
    return self._event_filter_console_keypress(event)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\frontend_widget.py", line 381, in _event_filter_console_keypress
    return super(FrontendWidget, self)._event_filter_console_keypress(event)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\console_widget.py", line 1166, in _event_filter_console_keypress
    self.execute(interactive = not shift_down)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\history_console_widget.py", line 47, in execute
    source, hidden, interactive)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\qtconsole\console_widget.py", line 630, in execute
    self._execute(source, hidden)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\hyperspyui\widgets\consolewidget.py", line 75, in _execute
    msg_id = self.kernel_client.execute(source, hidden)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\inprocess\client.py", line 102, in execute
    self._dispatch_to_kernel(msg)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\inprocess\client.py", line 172, in _dispatch_to_kernel
    idents, reply_msg = self.session.recv(stream, copy=False)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\jupyter_client\session.py", line 778, in recv
    msg_list = socket.recv_multipart(mode, copy=copy)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\site-packages\ipykernel\inprocess\socket.py", line 57, in recv_multipart
    return self.queue.get_nowait()
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\queue.py", line 192, in get_nowait
    return self.get(block=False)
  File "C:\Program Files\HyperSpy WinPython Bundle v1.3.0\python-3.5.1\lib\queue.py", line 161, in get
    raise Empty
queue.Empty
`

**Comment by thomasaarholt** [comment]
:) If you use three of those ticks before, and three after, it'll look a lot better :)
Very strange error

**Comment by ericpre** [comment]
The python stack has changed quite a bit since 2017 and we could not reproduce this error. Feel free to re-open if necessary.
