### ISSUE TITLE
Warnings when using savefig on hyperspy plots

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1976]
I'm getting a warning when saving figures using the notebook and ipympl backends. This does not occur if I create a plot using normal matplotlib, therefore I think the issue lies with us rather than mpl / notebook.

The plot still appears and is fully interactive. It is just a bit annoying since I'm creating a template workflow.

MWE:

```python
>>> %matplotlib ipympl
>>> hs.signals.Signal1D([1,2,3]).plot()
>>> plt.savefig('test.png')
Traceback (most recent call last):
  File "C:\Users\thomasaar\AppData\Local\conda\conda\envs\py36\lib\site-packages\matplotlib\cbook\__init__.py", line 388, in process
    proxy(*args, **kwargs)
  File "C:\Users\thomasaar\AppData\Local\conda\conda\envs\py36\lib\site-packages\matplotlib\cbook\__init__.py", line 228, in __call__
    return mtd(*args, **kwargs)
  File "z:\software\hyperspy\hyperspy\drawing\figure.py", line 56, in _on_draw
    canvas.draw_idle()
  File "C:\Users\thomasaar\AppData\Local\conda\conda\envs\py36\lib\site-packages\matplotlib\backends\backend_webagg_core.py", line 166, in draw_idle
    self.send_event("draw")
  File "C:\Users\thomasaar\AppData\Local\conda\conda\envs\py36\lib\site-packages\matplotlib\backends\backend_webagg_core.py", line 358, in send_event
    self.manager._send_event(event_type, **kwargs)
AttributeError: 'FigureCanvasNbAgg' object has no attribute 'manager'
```

**Comment by ericpre** [comment]
I can't reproduce with any backend. Can you make sure this is not related to the ipympl backend? The jupyter-matplotlib extension is at early stage development, so I would update to last version and check this first.

**Comment by ericpre** [comment]
If this is still an issue, it looks like this is one for jupyter-matplotlib.
