### ISSUE TITLE
tqdm RuntimeError with Samfire tests

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy#2077]
Since tqdm 4.25, we have the following `RuntimeError` when running the samfire tests:

```python
Exception ignored in: <bound method tqdm.__del__ of 104/|/100%|| 104/104 [02:02<00:00,  5.48it/s]>
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python3.6/site-packages/tqdm/_tqdm.py", line 885, in __del__
    self.close()
  File "/home/travis/miniconda/envs/testenv/lib/python3.6/site-packages/tqdm/_tqdm_notebook.py", line 227, in close
    super(tqdm_notebook, self).close(*args, **kwargs)
  File "/home/travis/miniconda/envs/testenv/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1090, in close
    self._decr_instances(self)
  File "/home/travis/miniconda/envs/testenv/lib/python3.6/site-packages/tqdm/_tqdm.py", line 454, in _decr_instances
    cls.monitor.exit()
  File "/home/travis/miniconda/envs/testenv/lib/python3.6/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/home/travis/miniconda/envs/testenv/lib/python3.6/threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```
as it can be seen in this [log](https://travis-ci.org/hyperspy/hyperspy/jobs/419700069) travis.

The error should be only for the progress bar, so this is not a big deal.

**Comment by francisco-dlp** [comment]
It seems to be a known tqdm bug, see https://github.com/tqdm/tqdm/issues/549#issuecomment-421361884 . However, I couldn't find an open issue tracking this bug.

**Comment by ericpre** [comment]
Yes, there are a few mentions of it on github. I can't look at this in the short term but it would good to more a minimum and simple example to reproduce this bug and report properly.

At least, we have a workaround now, which to install tqdm < 4.25. 
If anyone has an issue with this, try to run in a console:
```
pip install tqdm==4.24
```
use `conda install tqdm=4.24` instead if using the anaconda distribution.

**Comment by tjof2** [comment]
Pretty sure this can be closed @ericpre

**Comment by ericpre** [comment]
Yes, it seems that it is not happening anymore!
