### ISSUE TITLE
Converting axes between Celsius and Kelvin fails

### ISSUE THREAD

**Issue by nitrocalcite** [hyperspy/hyperspy#2360]
Firstly, awesome library, and thank you to all the contributors!
When I assign an axis an offset temperature unit and try to convert it, the conversation fails. Example:
```
sig = hs.signals.Signal2D(np.random.rand(1000).reshape((10,10,10)))
sig.axes_manager[0].units = 'celsius'
sig.axes_manager[0].convert_to_unit('kelvin')
```
The last line produces:
```
Traceback (most recent call last):
  File "C:\Users\nitrocalcite\Miniconda3\envs\PyX\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-35-bd9075fcb07f>", line 1, in <module>
    sig.axes_manager['Temperature'].convert_to_units("kelvin")
  File "C:\Users\nitrocalcite\Miniconda3\envs\PyX\lib\site-packages\hyperspy\axes.py", line 158, in convert_to_units
    out = self._convert_units(units, inplace=inplace)
  File "C:\Users\nitrocalcite\Miniconda3\envs\PyX\lib\site-packages\hyperspy\axes.py", line 125, in _convert_units
    scale_pint = self.scale * _ureg(self.units)
  File "C:\Users\nitrocalcite\Miniconda3\envs\PyX\lib\site-packages\pint\quantity.py", line 1172, in __mul__
    return self._mul_div(other, operator.mul)
  File "C:\Users\nitrocalcite\Miniconda3\envs\PyX\lib\site-packages\pint\quantity.py", line 102, in wrapped
    result = f(self, *args, **kwargs)
  File "C:\Users\nitrocalcite\Miniconda3\envs\PyX\lib\site-packages\pint\quantity.py", line 85, in wrapped
    result = f(self, *args, **kwargs)
  File "C:\Users\nitrocalcite\Miniconda3\envs\PyX\lib\site-packages\pint\quantity.py", line 1120, in _mul_div
    raise OffsetUnitCalculusError(self._units, getattr(other, "units", ""))
pint.errors.OffsetUnitCalculusError: Ambiguous operation with offset unit (degree_Celsius, ). See https://pint.readthedocs.io/en/latest/nonmult.html for guidance.

```

 It seems like HyperSpy wants to change its internal `axis.scale` property to the new unit, using multiplication, but `pint` does not understand how to multiply an offset unit like celsius by a number.  As a workaround, the conversion can be performed before constructing the signal.

I'm running Windows 10 using Miniconda: `hyperspy=1.5.2` `pint=0.11` `python=3.7.7`.  Anyone else experience similar behavior?

**Comment by thomasaarholt** [comment]
Interesting! This "error" originates from `pint`, and is due to there being two (or multiple) interpretations of what the result should be. Just quickly, as an example, consider someone who wants to add two temperatures, 100 C and 10 C together. 

100 C + 10 C = 110 C.

Alternatively, converting to kelvin:
373.15 kelvin + 283.15 kelvin = 656.3 kelvin = 383.15 C!

This depends on whether one is just "increasing" the temperature by 10 C or meaning to sum the two temperatures on an absolute scale. `pint` calls units like celsius for "delta units" (in the docs. In the error, it is called a offset unit).

The reason your example is raising an error, is for a similar reason. Hyperspy is performing a multiplication here: 
`scale_pint = self.scale * _ureg(self.units)`
where it is multiplying a delta unit (celsius) with the axis scale. Due to the above ambiguity, `pint` doesn't allow it by default.
To test it, you can try the following:

```python
from pint import UnitRegistry
ureg = UnitRegistry()
20 * ureg('celsius')
--- # error:
OffsetUnitCalculusError: Ambiguous operation with offset unit (degC).
```
I see two solutions to this:

We can either check for, and explicitly convert, all delta units to absolute units, and then back again. This sounds like a lot of work, so I'd prefer the second option, which is just setting the following argument to `UnitRegistry()`:

`ureg = UnitRegistry(autoconvert_offset_to_baseunit = True)`

[Quoting the `pint` docs:](https://pint.readthedocs.io/en/0.10.1/nonmult.html)
> Before all other multiplications, all divisions and in case of exponentiation [1] involving quantities with offset-units, pint will convert the quantities with offset units automatically to the corresponding base unit before performing the operation.

```python
from pint import UnitRegistry
ureg = UnitRegistry(autoconvert_offset_to_baseunit = True)
20 * ureg('celsius')
# 20 degC
```
