### ISSUE TITLE
`model.as_signal` is not working when using `component_list` and `parallel=True`

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy#2443]
The following example raises an error with `parallel=True`:

```python
s = hs.signals.Signal1D(np.random.random((10,100)))
m = s.create_model()
l1 = hs.model.components1D.Lorentzian(centre=20)
m.append(l1)
s2 = m.as_signal(component_list=[l1], parallel=True)
```
Error:
```python
Traceback (most recent call last):

  File "<ipython-input-2-c9621a70c23c>", line 5, in <module>
    s2 = m.as_signal(component_list=[l1], parallel=True)

  File "/home/eric/Dev/hyperspy/hyperspy/model.py", line 541, in as_signal
    _ = next(_map)

  File "/opt/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()

  File "/opt/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()

  File "/opt/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception

  File "/opt/miniconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)

  File "/home/eric/Dev/hyperspy/hyperspy/model.py", line 538, in <lambda>
    show_progressbar=thing[2] + 1 if show_progressbar else False),

  File "/home/eric/Dev/hyperspy/hyperspy/model.py", line 563, in _as_signal_iter
    for x in component_list]

  File "/home/eric/Dev/hyperspy/hyperspy/model.py", line 563, in <listcomp>
    for x in component_list]

  File "/home/eric/Dev/hyperspy/hyperspy/model.py", line 336, in _get_component
    raise ValueError("The component is not in the model.")

ValueError: The component is not in the model.
```

**Comment by tjof2** [comment]
@ericpre  while investigating #1604, I don't see what benefits `parallel=True` brings to this function. 

On my machine:

```python
import hyperspy.api as hs
import numpy as np

def create_test_model():
    rng = np.random.RandomState(123)

    s = hs.signals.Signal1D(rng.uniform(size=(32,32,32,32)))
    m = s.create_model()
    l1 = hs.model.components1D.Lorentzian(centre=20)
    l2 = hs.model.components1D.Lorentzian(centre=10)
    m.append(l1)
    m.append(l2)
    
    return m

m1 = create_test_model()
%timeit m1.as_signal(parallel=True, show_progressbar=False)
# 19.9 s ± 1.44 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

m2 = create_test_model()
%timeit m2.as_signal(parallel=False, show_progressbar=False)
# 8.98 s ± 93.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

This is perhaps not surprising - calling this function with `parallel=True` uses thread-based parallelism (`concurrent.futures.ThreadPoolExecutor`) here: https://github.com/hyperspy/hyperspy/blob/d7d52ac4c99eb59933b94bda2319a193a83eeb5b/hyperspy/model.py#L565-L572. However, the code it runs is pure Python, so won't release the GIL.

I'd propose deprecating or removing `parallel=True` as an option here entirely, which would fix #1604 at the same time.
