### ISSUE TITLE
Hyperspy test with pytest failed on i586 microarchitecture

### ISSUE THREAD

**Issue by kevinsmia1939** [hyperspy/hyperspy#2476]
Hello,

I'm packaging python-thewalrus on linux openSUSE Tumbleweed.
Testing hyperspy with pytest failed on i586 microarchitecture but pass on x86.

OverflowError suggest that it might be due to limitation of 32 bit arch?
There are AssertionError as well, could it be related?

Would it be better kust to not package for 32 bit?

Full log here: https://build.opensuse.org/build/home:andythe_great/openSUSE_Tumbleweed/i586/python-hyperspy/_log

Thanks.

```
[ 1672s] =================================== FAILURES ===================================
[ 1672s] ________________________ test_serial_date_to_ISO_format ________________________
[ 1672s] 
[ 1672s]     def test_serial_date_to_ISO_format():
[ 1672s]         iso_1 = dtt.serial_date_to_ISO_format(serial1)
[ 1672s]         dt1_local = dt1.astimezone(tz.tzlocal())
[ 1672s]         assert iso_1[0] == dt1_local.date().isoformat()
[ 1672s]         assert iso_1[1] == dt1_local.time().isoformat()
[ 1672s]         assert iso_1[2] == dt1_local.tzname()
[ 1672s]     
[ 1672s] >       iso_2 = dtt.serial_date_to_ISO_format(serial2)
[ 1672s] 
[ 1672s] hyperspy/tests/misc/test_date_time_tools.py:129: 
[ 1672s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[ 1672s] hyperspy/misc/date_time_tools.py:147: in serial_date_to_ISO_format
[ 1672s]     dt_local = dt_utc.astimezone(tz.tzlocal())
[ 1672s] /usr/lib/python3.8/site-packages/dateutil/tz/_common.py:144: in fromutc
[ 1672s]     return f(self, dt)
[ 1672s] /usr/lib/python3.8/site-packages/dateutil/tz/_common.py:261: in fromutc
[ 1672s]     _fold = self._fold_status(dt, dt_wall)
[ 1672s] /usr/lib/python3.8/site-packages/dateutil/tz/_common.py:196: in _fold_status
[ 1672s]     if self.is_ambiguous(dt_wall):
[ 1672s] /usr/lib/python3.8/site-packages/dateutil/tz/tz.py:254: in is_ambiguous
[ 1672s]     naive_dst = self._naive_is_dst(dt)
[ 1672s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[ 1672s] 
[ 1672s] self = tzlocal()
[ 1672s] dt = datetime.datetime(2124, 3, 25, 15, 4, 48, 1, tzinfo=tzlocal())
[ 1672s] 
[ 1672s]     def _naive_is_dst(self, dt):
[ 1672s]         timestamp = _datetime_to_timestamp(dt)
[ 1672s] >       return time.localtime(timestamp + time.timezone).tm_isdst
[ 1672s] E       OverflowError: timestamp out of range for platform time_t
[ 1672s] 
[ 1672s] /usr/lib/python3.8/site-packages/dateutil/tz/tz.py:260: OverflowError
[ 1672s] ________________________ test_ISO_format_to_serial_date ________________________
[ 1672s] 
[ 1672s]     def test_ISO_format_to_serial_date():
[ 1672s]         res1 = dtt.ISO_format_to_serial_date(
[ 1672s]             dt1.date().isoformat(), dt1.time().isoformat(), timezone=dt1.tzname())
[ 1672s]         assert_allclose(res1, serial1, atol=1E-5)
[ 1672s] >       dt = dt2.astimezone(tz.tzlocal())
[ 1672s] 
[ 1672s] hyperspy/tests/misc/test_date_time_tools.py:149: 
[ 1672s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[ 1672s] /usr/lib/python3.8/site-packages/dateutil/tz/_common.py:144: in fromutc
[ 1672s]     return f(self, dt)
[ 1672s] /usr/lib/python3.8/site-packages/dateutil/tz/_common.py:261: in fromutc
[ 1672s]     _fold = self._fold_status(dt, dt_wall)
[ 1672s] /usr/lib/python3.8/site-packages/dateutil/tz/_common.py:196: in _fold_status
[ 1672s]     if self.is_ambiguous(dt_wall):
[ 1672s] /usr/lib/python3.8/site-packages/dateutil/tz/tz.py:254: in is_ambiguous
[ 1672s]     naive_dst = self._naive_is_dst(dt)
[ 1672s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[ 1672s] 
[ 1672s] self = tzlocal()
[ 1672s] dt = datetime.datetime(2124, 3, 25, 15, 4, 48, tzinfo=tzlocal())
[ 1672s] 
[ 1672s]     def _naive_is_dst(self, dt):
[ 1672s]         timestamp = _datetime_to_timestamp(dt)
[ 1672s] >       return time.localtime(timestamp + time.timezone).tm_isdst
[ 1672s] E       OverflowError: timestamp out of range for platform time_t
[ 1672s] 
[ 1672s] /usr/lib/python3.8/site-packages/dateutil/tz/tz.py:260: OverflowError
[ 1672s] __________________________ TestShift1D.test_crop_left __________________________
[ 1672s] 
[ 1672s] self = <hyperspy.tests.signal.test_1D_tools.TestShift1D object at 0x761faf40>
[ 1672s] 
[ 1672s]     def test_crop_left(self):
[ 1672s]         s = self.s
[ 1672s]         s.shift1D(np.array((0.01)), crop=True)
[ 1672s] >       assert (
[ 1672s]             tuple(
[ 1672s]                 s.axes_manager[0].axis) == tuple(
[ 1672s]                 np.arange(
[ 1672s]                     0.2, 2., 0.2)))
[ 1672s] E       AssertionError: assert (0.2, 0.4, 0....1.0, 1.2, ...) == (0.2, 0.4, 0....00000002, ...)
[ 1672s] E         At index 5 diff: 1.2 != 1.2000000000000002
[ 1672s] E         Full diff:
[ 1672s] E           (
[ 1672s] E            0.2,
[ 1672s] E            0.4,
[ 1672s] E            0.6000000000000001,
[ 1672s] E            0.8,...
[ 1672s] E         
[ 1672s] E         ...Full output truncated (8 lines hidden), use '-vv' to show
[ 1672s] 
[ 1672s] hyperspy/tests/signal/test_1D_tools.py:116: AssertionError
[ 1672s] ----------------------------- Captured stderr call -----------------------------
[ 1672s] Exception ignored in: <function tqdm.__del__ at 0x9f257970>
[ 1672s] Traceback (most recent call last):
[ 1672s]   File "/usr/lib/python3.8/site-packages/tqdm/std.py", line 1087, in __del__
[ 1672s]     self.close()
[ 1672s]   File "/usr/lib/python3.8/site-packages/tqdm/notebook.py", line 244, in close
[ 1672s]     self.sp(bar_style='danger')
[ 1672s] AttributeError: 'tqdm_notebook' object has no attribute 'sp'
[ 1672s] 
[ 1672s] 
[ 1672s]   0%|          | 0/1 [00:00<?, ?it/s][A
[ 1672s] 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 [00:00<00:00, 408.20it/s]
[ 1672s] _______________________ TestShift1D.test_lazy_crop_left ________________________
[ 1672s] 
[ 1672s] self = <hyperspy.tests.signal.test_1D_tools.TestShift1D object at 0x91152e08>
[ 1672s] 
[ 1672s]     def test_crop_left(self):
[ 1672s]         s = self.s
[ 1672s]         s.shift1D(np.array((0.01)), crop=True)
[ 1672s] >       assert (
[ 1672s]             tuple(
[ 1672s]                 s.axes_manager[0].axis) == tuple(
[ 1672s]                 np.arange(
[ 1672s]                     0.2, 2., 0.2)))
[ 1672s] E       AssertionError: assert (0.2, 0.4, 0....1.0, 1.2, ...) == (0.2, 0.4, 0....00000002, ...)
[ 1672s] E         At index 5 diff: 1.2 != 1.2000000000000002
[ 1672s] E         Full diff:
[ 1672s] E           (
[ 1672s] E            0.2,
[ 1672s] E            0.4,
[ 1672s] E            0.6000000000000001,
[ 1672s] E            0.8,...
[ 1672s] E         
[ 1672s] E         ...Full output truncated (8 lines hidden), use '-vv' to show
[ 1672s] 
[ 1672s] hyperspy/tests/signal/test_1D_tools.py:116: AssertionError
```

**Comment by ericpre** [comment]
It looks like these failures could be fixed, but since we don't test on this architecture, the problem may happen again, so I am not sure if there is any point in fixing it, without running the test suite for this architecture as part of our CI...

**Comment by tjof2** [comment]
I'd imagine `test_crop_left()` isn't the only example of using `==` to compare floats either, which clearly is an issue on this architecture

**Comment by kevinsmia1939** [comment]
> It looks like these failures could be fixed, but since we don't test on this architecture, the problem may happen again, so I am not sure if there is any point in fixing it, without running the test suite for this architecture as part of our CI...

Thanks for reply, I think it is safe to not support i586 then?

**Comment by ericpre** [comment]
Testing on 32 bit with a different architecture may be good enough to cover this, but what is the current main use of this architecture? It looks like this is a ~20 years old? https://en.wikipedia.org/wiki/P5_(microarchitecture)

**Comment by kevinsmia1939** [comment]
> Testing on 32 bit with a different architecture may be good enough to cover this, but what is the current main use of this architecture? It looks like this is a ~20 years old? https://en.wikipedia.org/wiki/P5_(microarchitecture)

No specific use at the moment. If the issue are easy to fix, I think it is worth fixing it. But if you don't feel like supporting it then I will not package hyperspy for i586.

**Comment by kevinsmia1939** [comment]
I just disable build for i586 I don't think we need it.
