### ISSUE TITLE
Setting signal type lose events connection

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy#2612]
When using the `set_signal_type`, a new instance is created and the connected events are not connected to the new instance.

```python
import matplotlib.pyplot as plt
import hyperspy.api as hs

s = hs.datasets.artificial_data.get_core_loss_eels_line_scan_signal()
s.plot()
s.set_signal_type('EELS')
plt.close('all')
```
Give the following traceback
```python
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 224, in process
    func(*args, **kwargs)
  File "/home/eric/Dev/hyperspy/hyperspy/drawing/utils.py", line 194, in function_wrapper
    function()
  File "/home/eric/Dev/hyperspy/hyperspy/drawing/signal1d.py", line 175, in _on_close
    super(Signal1DFigure, self)._on_close()
  File "/home/eric/Dev/hyperspy/hyperspy/drawing/figure.py", line 117, in _on_close
    self.events.closed.trigger(obj=self)
  File "<string>", line 4, in trigger
  File "/home/eric/Dev/hyperspy/hyperspy/events.py", line 422, in trigger
    function(**{kw: kwargs.get(kw, None) for kw in kwsl})
  File "/home/eric/Dev/hyperspy/hyperspy/signal.py", line 2672, in <lambda>
    lambda: self.events.data_changed.disconnect(self.update_plot),
  File "/home/eric/Dev/hyperspy/hyperspy/events.py", line 392, in disconnect
    raise ValueError("The %s function is not connected to %s." %
ValueError: The <bound method BaseSignal.update_plot of <EELSSpectrum, title: Artifical core loss EEL spectrum, dimensions: (12|400)>> function is not connected to <hyperspy.events.Event: Event that triggers when the data has changed: set()>.
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 224, in process
    func(*args, **kwargs)
  File "/home/eric/Dev/hyperspy/hyperspy/drawing/utils.py", line 194, in function_wrapper
    function()
  File "/home/eric/Dev/hyperspy/hyperspy/drawing/signal1d.py", line 175, in _on_close
    super(Signal1DFigure, self)._on_close()
  File "/home/eric/Dev/hyperspy/hyperspy/drawing/figure.py", line 117, in _on_close
    self.events.closed.trigger(obj=self)
  File "<string>", line 4, in trigger
  File "/home/eric/Dev/hyperspy/hyperspy/events.py", line 422, in trigger
    function(**{kw: kwargs.get(kw, None) for kw in kwsl})
  File "/home/eric/Dev/hyperspy/hyperspy/signal.py", line 2672, in <lambda>
    lambda: self.events.data_changed.disconnect(self.update_plot),
  File "/home/eric/Dev/hyperspy/hyperspy/events.py", line 392, in disconnect
    raise ValueError("The %s function is not connected to %s." %
ValueError: The <bound method BaseSignal.update_plot of <EELSSpectrum, title: Artifical core loss EEL spectrum, dimensions: (12|400)>> function is not connected to <hyperspy.events.Event: Event that triggers when the data has changed: set()>.
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 224, in process
    func(*args, **kwargs)
  File "/home/eric/Dev/hyperspy/hyperspy/drawing/utils.py", line 194, in function_wrapper
    function()
  File "/home/eric/Dev/hyperspy/hyperspy/drawing/signal1d.py", line 175, in _on_close
    super(Signal1DFigure, self)._on_close()
  File "/home/eric/Dev/hyperspy/hyperspy/drawing/figure.py", line 117, in _on_close
    self.events.closed.trigger(obj=self)
  File "<string>", line 4, in trigger
  File "/home/eric/Dev/hyperspy/hyperspy/events.py", line 422, in trigger
    function(**{kw: kwargs.get(kw, None) for kw in kwsl})
  File "/home/eric/Dev/hyperspy/hyperspy/signal.py", line 2672, in <lambda>
    lambda: self.events.data_changed.disconnect(self.update_plot),
  File "/home/eric/Dev/hyperspy/hyperspy/events.py", line 392, in disconnect
    raise ValueError("The %s function is not connected to %s." %
ValueError: The <bound method BaseSignal.update_plot of <EELSSpectrum, title: Artifical core loss EEL spectrum, dimensions: (12|400)>> function is not connected to <hyperspy.events.Event: Event that triggers when the data has changed: set()>.()>.
```

**Comment by ericpre** [comment]
Fixed in https://github.com/hyperspy/hyperspy/pull/2683.
