### ISSUE TITLE
find_peaks() won't work for the laplacian/difference of gaussian methods

### ISSUE THREAD

**Issue by pc494** [hyperspy/hyperspy#2622]
Running `find_peaks()` in a fairly normal way:

```
 dp_rb.find_peaks(method='laplacian_of_gaussian', 
                         min_sigma=0.7,
                         max_sigma=10,
                         num_sigma=30, 
                         threshold=0.046, 
                         overlap=0.5, 
                         log_scale=False,
                         exclude_border=True)

```
Throws an error:

```python 
TraitError: The 'method' trait of a PeaksFinder2D instance must be 'Local max' or 'Max' or
'Minmax' or 'Zaefferer' or 'Stat' or 'Laplacian of Gaussian' or 'Difference of Gaussian' 
or 'Template matching', but a value of 'Laplacian of gaussian' <class 'str'> was specified.
```

From elsewhere in the same stacktrace we have:

```python
~/miniconda3/envs/miniconda-1/lib/python3.8/site-packages/hyperspy/signal_tools.py in __init__(self, signal, method, peaks, **kwargs)
   1946             self.xc_template = kwargs['template']
   1947         if method is not None:
-> 1948             self.method = method.capitalize().replace('_', ' ')
```

from which the output will be `'Laplacian of gaussian'` (as capitalize acts on only the first position of a string) - I assume that the dictionary against which it's later checked is capitalized for GUI reasons.

Thoughts?

**Comment by ericpre** [comment]
Indeed, it doesn't play well with the GUI...

It works only without the GUI:
```python
n = 256
s = hs.signals.Signal2D(np.zeros([n]*2))
s.find_peaks(method='laplacian_of_gaussian', interactive=False)
```

Do you want to make a PR to fix it?

For the record, a minimum example is:
```python
import numpy as np
import hyperspy.api as hs

n = 256
s = hs.signals.Signal2D(np.zeros([n]*2))
s.find_peaks(method='laplacian_of_gaussian')
```
which gives:
```python
Traceback (most recent call last):

  File "<ipython-input-9-4bd203fc9013>", line 3, in <module>
    s.find_peaks(method='laplacian_of_gaussian')

  File "/home/eric/Dev/hyperspy/hyperspy/_signals/signal2d.py", line 920, in find_peaks
    pf2D = PeaksFinder2D(self, method=method, peaks=peaks, **kwargs)

  File "/home/eric/Dev/hyperspy/hyperspy/signal_tools.py", line 1945, in __init__
    self.method = method.capitalize().replace('_', ' ')

  File "/opt/miniconda3/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(

TraitError: The 'method' trait of a PeaksFinder2D instance must be 'Local max' or 'Max' or 'Minmax' or 'Zaefferer' or 'Stat' or 'Laplacian of Gaussian' or 'Difference of Gaussian' or 'Template matching', but a value of 'Laplacian of gaussian' <class 'str'> was specified.
```
And by trying to use the valid value as given in the error message:
```python
import numpy as np
import hyperspy.api as hs

n = 256
s = hs.signals.Signal2D(np.zeros([n]*2))
s.find_peaks(method='Laplacian of Gaussian')
```
we get:
```python
Traceback (most recent call last):

  File "<ipython-input-10-41a6928e8ea1>", line 3, in <module>
    s.find_peaks(method='Laplacian of Gaussian')

  File "/home/eric/Dev/hyperspy/hyperspy/_signals/signal2d.py", line 910, in find_peaks
    raise NotImplementedError(f"The method `{method}` is not "

NotImplementedError: The method `Laplacian of Gaussian` is not implemented. See documentation for available implementations.
```

**Comment by pc494** [comment]
I'm happy to do this. Is addressing the problem at the GUI level sufficient? Taking:

https://github.com/hyperspy/hyperspy/blob/8551bf5cec2aeb940558dbbce2df153a4b174d47/hyperspy/signal_tools.py#L2002-L2003

and adding an extra `if` block?

ie:

```python
if method is not None and is not ('laplcian_' or 'diff'):
      self.method = method.capitalize().replace('_', ' ') 
elif method is ('laplcian' or 'diff'):
```

**Comment by ericpre** [comment]
We had a similar issue in https://github.com/hyperspy/hyperspy/pull/2465 and maybe the best is use a dictionary to do the mapping as suggested by @tjof2 in https://github.com/hyperspy/hyperspy/pull/2465#issuecomment-668661976?

An alternative would be to have the allowed parameter matching the GUIs ones, but this would break the API.

**Comment by pc494** [comment]
It's annoying but I do think that `differences_of_gaussians` is correct for non-interactive and `Differences_of_Gaussians` for the GUI. Given the number of potential combinations I'm going to go with the dictionary option.

Fair warning, it might be a couple of days before I get to it.

**Comment by ericpre** [comment]
Done in #2647.
