### ISSUE TITLE
Template Matching Error

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2666]
Trying out the template matching option to `find_peaks` raises the following issue on this Signal2D  of shape `(|122, 173)`: [template_match.zip](https://github.com/hyperspy/hyperspy/files/6122073/template_match.zip)

I use a motif taken from a roi on the signal:
![Figure_Sb_Signal](https://user-images.githubusercontent.com/2721423/110770608-cdb7b100-8259-11eb-84c5-90ee1466dc77.png)

```python
s = hs.load("template_match.hspy")
roi = hs.roi.RectangularROI(left=-0.929692, top=-1.26298, right=0.26312, bottom=-0.210496)
motif = roi(s)

s.find_peaks(method='template_matching', template=motif.data)
```

```python
ERROR:traits:Exception occurred in traits notification handler for object: <hyperspy.signal_tools.PeaksFinder2D object at 0x00000157C9F46DB0>, trait: method, old value: Local max, new value: Template matching
Traceback (most recent call last):
  File "C:\Users\thomasaar\Miniconda3\envs\gpu\lib\site-packages\traits\trait_notifiers.py", line 342, in __call__
    self.handler(*args)
  File "c:\users\thomasaar\documents\github\hyperspy\hyperspy\signal_tools.py", line 2021, in _method_changed
    self._update_peak_finding(method=new)
  File "c:\users\thomasaar\documents\github\hyperspy\hyperspy\signal_tools.py", line 2016, in _update_peak_finding
    self._plot_markers()
  File "c:\users\thomasaar\documents\github\hyperspy\hyperspy\signal_tools.py", line 2049, in _plot_markers
    peaks_markers = self._peaks_to_marker()
  File "c:\users\thomasaar\documents\github\hyperspy\hyperspy\signal_tools.py", line 2060, in _peaks_to_marker
    marker_list = [Point(x=x_axis.index2value(x),
  File "c:\users\thomasaar\documents\github\hyperspy\hyperspy\signal_tools.py", line 2060, in <listcomp>
    marker_list = [Point(x=x_axis.index2value(x),
  File "c:\users\thomasaar\documents\github\hyperspy\hyperspy\axes.py", line 581, in index2value
    return self.axis[index]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-80-e1a3ebae31b7> in <module>
      2 roi = hs.roi.RectangularROI(left=-0.929692, top=-1.26298, right=0.26312, bottom=-0.210496)
      3 motif = roi(s)
----> 4 s.find_peaks(method='template_matching', template=motif.data)

c:\users\thomasaar\documents\github\hyperspy\hyperspy\_signals\signal2d.py in find_peaks(self, method, interactive, current_index, show_progressbar, parallel, max_workers, display, toolkit, **kwargs)
    918             peaks = BaseSignal(np.empty(self.axes_manager.navigation_shape),
    919                                axes=axes_dict)
--> 920             pf2D = PeaksFinder2D(self, method=method, peaks=peaks, **kwargs)
    921             pf2D.gui(display=display, toolkit=toolkit)
    922         elif current_index:

c:\users\thomasaar\documents\github\hyperspy\hyperspy\signal_tools.py in __init__(self, signal, method, peaks, **kwargs)
   1998             self.xc_template = kwargs['template']
   1999         if method is not None:
-> 2000             self.method = method.capitalize().replace('_', ' ')
   2001         self._parse_paramaters_initial_values(**kwargs)
   2002         self._update_peak_finding()

~\Miniconda3\envs\gpu\lib\site-packages\traits\trait_notifiers.py in __call__(self, object, trait_name, old, new)
    346                         object, trait_name, old, new, self.handler, exception=e
    347                     )
--> 348                 handle_exception(object, trait_name, old, new)
    349             else:
    350                 if _post_change_event_tracer is not None:

~\Miniconda3\envs\gpu\lib\site-packages\traits\trait_notifiers.py in _handle_exception(self, object, trait_name, old, new)
    147             excp, TraitNotificationError
    148         ):
--> 149             raise excp
    150 
    151     def _get_handlers(self):

~\Miniconda3\envs\gpu\lib\site-packages\traits\trait_notifiers.py in __call__(self, object, trait_name, old, new)
    340             try:
    341                 # Call the handler.
--> 342                 self.handler(*args)
    343             except Exception as e:
    344                 if _post_change_event_tracer is not None:

c:\users\thomasaar\documents\github\hyperspy\hyperspy\signal_tools.py in _method_changed(self, old, new)
   2019         if new == 'Template matching' and self.xc_template is None:
   2020             raise RuntimeError('The "template" argument is required.')
-> 2021         self._update_peak_finding(method=new)
   2022 
   2023     def _parameter_changed(self, old, new):

c:\users\thomasaar\documents\github\hyperspy\hyperspy\signal_tools.py in _update_peak_finding(self, method)
   2014             method = self.method.lower().replace(' ', '_')
   2015         self._find_peaks_current_index(method=method)
-> 2016         self._plot_markers()
   2017 
   2018     def _method_changed(self, old, new):

c:\users\thomasaar\documents\github\hyperspy\hyperspy\signal_tools.py in _plot_markers(self)
   2047         if self.signal._plot is not None and self.signal._plot.is_active:
   2048             self.signal._plot.signal_plot.remove_markers(render_figure=True)
-> 2049         peaks_markers = self._peaks_to_marker()
   2050         self.signal.add_marker(peaks_markers, render_figure=True)
   2051 

c:\users\thomasaar\documents\github\hyperspy\hyperspy\signal_tools.py in _peaks_to_marker(self, markersize, add_numbers, color)
   2058         y_axis = self.signal.axes_manager.signal_axes[1]
   2059 
-> 2060         marker_list = [Point(x=x_axis.index2value(x),
   2061                              y=y_axis.index2value(y),
   2062                              color=color,

c:\users\thomasaar\documents\github\hyperspy\hyperspy\signal_tools.py in <listcomp>(.0)
   2058         y_axis = self.signal.axes_manager.signal_axes[1]
   2059 
-> 2060         marker_list = [Point(x=x_axis.index2value(x),
   2061                              y=y_axis.index2value(y),
   2062                              color=color,

c:\users\thomasaar\documents\github\hyperspy\hyperspy\axes.py in index2value(self, index)
    579             return self.axis[index.ravel()].reshape(index.shape)
    580         else:
--> 581             return self.axis[index]
    582 
    583     def calibrate(self, value_tuple, index_tuple, modify_calibration=True):

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by thomasaarholt** [comment]
Sticking some print statements in signal_tools.py before line 2060, I see that the the peaks found were nans:

```python
        # line 2056...
        x_axis = self.signal.axes_manager.signal_axes[0]
        y_axis = self.signal.axes_manager.signal_axes[1]
        print(self.peaks)
        print(self.peaks.data)
        for x, y in zip(self.peaks.data[:, 1], self.peaks.data[:, 0]):
            print(x,y)
```

```
<BaseSignal, title: , dimensions: (|)>
[[nan nan]]
nan nan
```
Would be great if someone who is familiar with the code could take a look, as this is very useful functionality.

**Comment by ericpre** [comment]
Which branch is it? There are some fixes related to this in the `RELEASE_next_patch` branch, can you confirm this is not fixed on RnP?

**Comment by thomasaarholt** [comment]
It works on RELEASE_next_patch. I was using an older version of _minor. 

Thanks @ericpre, this looks super good!
