### ISSUE TITLE
FEI navcam tifs cannot be opened

### ISSUE THREAD

**Issue by jat255** [hyperspy/hyperspy#2941]
#### Describe the bug
TIF-format images saved by FEI FIB/SEMs cannot be opened

#### To Reproduce

Try to open the attached .tif file:

```python
hs.load('51722 Nav-Cam.tif')

WARNING:matplotlib.font_manager:Matplotlib is building the font cache; this may take a moment.
ERROR:hyperspy.io:If this file format is supported, please report this error to the HyperSpy developers.
Traceback (most recent call last):
  File "/home/jat/git_repos/hyperspy/hyperspy/io_plugins/tiff.py", line 222, in _read_serie
    axes = _parse_scale_unit(tiff, page, op, shape, force_read_resolution, names, **kwds)
  File "/home/jat/git_repos/hyperspy/hyperspy/io_plugins/tiff.py", line 713, in _parse_scale_unit
    axes = _axes_fei(tiff, op, shape, names)
  File "/home/jat/git_repos/hyperspy/hyperspy/io_plugins/tiff.py", line 351, in _axes_fei
    scales['x'] = float(op['fei_metadata']['Scan']['PixelWidth'])
KeyError: 'Scan'
```

#### Expected behavior

Metadata should be ignored if not present, rather than causing a crash.

#### Python environement:
 - HyperSpy version: `RELEASE_next_minor`
 - Python version: Any

#### Additional context

Basically, the issue is that there is no `[Scan]` section for Navcam optical images, so it attempts to use the FEI reader, but it fails because of no `[Scan]` key in the metadata dictionary.

[navcam test.tar.gz](https://github.com/hyperspy/hyperspy/files/8719488/navcam.test.tar.gz)
(this image is blacked out, but the metadata is intact)

**Comment by jat255** [comment]
Here's the metadata embedded in that file:

```ini
Date=05/17/2022
Time=09:07:08 AM
User=user
UserText=USER TEXTFOR NAVCAM FIB  
UserTextUnicode=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

[System]
Type=DualBeam
Dnumber=9920003
Software=5.5.1.3318
BuildNr=3318
Source=FEG
Column=Elstar
FinalLens=Elstar
Chamber=xT-SDB
Stage=6inch
Pump=TMP
ESEM=no
Aperture=AVA
Scan=PIA 3.0
Acq=PIA 3.0
EucWD=0.004
SystemType=Helios NanoLab 660
DisplayWidth=0.373
DisplayHeight=0.303

[Beam]
HV=
Spot=
StigmatorX=
StigmatorY=
BeamShiftX=
BeamShiftY=
ScanRotation=0.00840385
ImageMode=
FineStageBias=
Beam=IRBeam
Scan=

[IRBeam]
HFW=0.202732
VFW=0.135155
StageX=-0.00126661
StageY=0.002136
StageZ=0
StageR=1.07874
StageTa=6.54498e-006
StageTb=0
WD=-1.2e-005
ScanRotation=0.00840385
SiDepth=
n=

[GIS]
Number=4

[GIS1]
GasType=Ins dep
HeaterState=Offline
NeedleState=Retracted
GasFlow=Off
Port=G1

[GIS2]
GasType=Au dep
HeaterState=Offline
NeedleState=Retracted
GasFlow=Off
Port=G2

[GIS3]
GasType=
HeaterState=
NeedleState=
GasFlow=
Port=

[GIS4]
GasType=
HeaterState=
NeedleState=
GasFlow=
Port=

[Stage]
StageX=0.0699197
StageY=0.000811186
StageZ=0
StageR=1.07874
StageT=6.54498e-006
StageTb=0
SpecTilt=
ActiveStage=Bulk
WorkingDistance=-1.2e-005

[Image]
DigitalContrast=0.661978
DigitalBrightness=0
DigitalGamma=0.958
Average=0
Integrate=0
ResolutionX=768
ResolutionY=512
DriftCorrected=
ZoomFactor=1.0
ZoomPanX=0.5
ZoomPanY=0.5
MagCanvasRealWidth=0.14920
MagnificationMode=3
ScreenMagCanvasRealWidth=0.14920
ScreenMagnificationMode=3
PostProcessing=None
Transformation=None

[Vacuum]
ChPressure=
Gas=
UserMode=High vacuum
Humidity=

[Specimen]
Temperature=
SpecimenCurrent=-6.9e-013

[Detectors]
Number=1
Name=Nav-Cam
Mode=None

[Nav-Cam]

[Accessories]
Number=0

[EBeamDeceleration]
ModeOn=Off
LandingEnergy=5000
ImmersionRatio=1
StageBias=0

[PrivateFei]
BitShift=0
DataBarSelected=DateTime x y HFW det Label MicronBar
DataBarAvailable=DateTime HFW x y z det zoom Label MicronBar
TimeOfCreation=17.05.2022 09:07:08
DatabarHeight=39

[MultiGIS]
Count=1

[MultiGISUnit1]
Port=4
NozzleState=Retracted

[MultiGISGas1]
GasName=N/A
DutyCycle=0
GasState=Off

[MultiGISGas2]
GasName=Pt
DutyCycle=100
GasState=Off

[MultiGISGas3]
GasName=H2O
DutyCycle=0
GasState=Off

[MultiGISGas4]
GasName=C
DutyCycle=80
GasState=Off

[MultiGISGas5]
GasName=W
DutyCycle=0
GasState=Off

[MultiGISGas6]
GasName=TEOS
DutyCycle=0
GasState=Off

[HiResIllumination]
BrightFieldIsOn=
BrightFieldValue=
DarkFieldIsOn=
DarkFieldValue=
```

**Comment by ericpre** [comment]
Done in #2942.
