### ISSUE TITLE
`zspy` metadata saving error: `np.int` dtype

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#2955]
Having a signal with metadata with the dtype `np.int8`, `np.int16`, `np.int32`, `np.int64`, `np.uint8`, `np.uint16`, `np.uint32` or `np.uint64` gives an error when saving to `zspy`. It works fine with `hspy`.

Example of this:

```python
import numpy as np
import hyperspy.api as hs
s = hs.signals.Signal1D(np.zeros(100))
s.metadata.test = np.int64(7)
s.save("test.hspy", overwrite=True) # Work fine
s.save("test.zspy", overwrite=True) # Gives error
```

<details><summary>Error message</summary>
<p>

```python
ERROR:hyperspy.io_plugins._hierarchical:The writer could not write the following information in the file: test : 7
Traceback (most recent call last):
  File "hyperspy/hyperspy/io_plugins/_hierarchical.py", line 786, in dict2group
    group.attrs[key] = value
  File "lib/python3.9/site-packages/zarr/attrs.py", line 79, in __setitem__
    self._write_op(self._setitem_nosync, item, value)
  File "lib/python3.9/site-packages/zarr/attrs.py", line 73, in _write_op
    return f(*args, **kwargs)
  File "lib/python3.9/site-packages/zarr/attrs.py", line 90, in _setitem_nosync
    self._put_nosync(d)
  File "lib/python3.9/site-packages/zarr/attrs.py", line 112, in _put_nosync
    self.store[self.key] = json_dumps(d)
  File "lib/python3.9/site-packages/zarr/util.py", line 38, in json_dumps
    return json.dumps(o, indent=4, sort_keys=True, ensure_ascii=True,
  File "lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "lib/python3.9/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "lib/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "lib/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int64 is not JSON serializable
```

</p>
</details>

#### Python environement:
 - HyperSpy version: 1.7.1.dev (most recent RELEASE_next_patch)
 - Python version: 3.9.12
 - Zarr version: 2.11.3

**Comment by ericpre** [comment]
This is zarr issue which is fixed in https://github.com/zarr-developers/zarr-python/pull/933.

**Comment by magnunor** [comment]
ok, nice! For future reference, the aforementioned fix should be a part of the (next?) `zarr` release, which is `2.12.0`.
