### ISSUE TITLE
s.remove_background() Import error

### ISSUE THREAD

**Issue by ydlee1227** [hyperspy/hyperspy#3058]
Import error occured for s.remove_background()
ImportError: Cannot import 'None' with 'import_module('numexpr')' command

ERROR:traits:Exception occurred in traits notification handler for object: <hyperspy.signal_tools.BackgroundRemoval object at 0x000001D9435AC5E0>, trait: background_type, old value: Doniach, new value: Power law
Traceback (most recent call last):
  File "C:\Users\yd2.lee\AppData\Local\Miniforge3\lib\site-packages\traits\trait_notifiers.py", line 342, in __call__
    self.handler(*args)
  File "C:\Users\yd2.lee\AppData\Local\Miniforge3\lib\site-packages\hyperspy\signal_tools.py", line 1508, in _background_type_changed
    self.set_background_estimator()
  File "C:\Users\yd2.lee\AppData\Local\Miniforge3\lib\site-packages\hyperspy\signal_tools.py", line 1495, in set_background_estimator
    self.background_estimator, self.bg_line_range = _get_background_estimator(
  File "C:\Users\yd2.lee\AppData\Local\Miniforge3\lib\site-packages\hyperspy\signal_tools.py", line 1677, in _get_background_estimator
    background_estimator = components1d.PowerLaw()
  File "C:\Users\yd2.lee\AppData\Local\Miniforge3\lib\site-packages\hyperspy\_components\power_law.py", line 67, in __init__
    super().__init__(
  File "C:\Users\yd2.lee\AppData\Local\Miniforge3\lib\site-packages\hyperspy\_components\expression.py", line 177, in __init__
    self.compile_function(module=module, position=position)
  File "C:\Users\yd2.lee\AppData\Local\Miniforge3\lib\site-packages\hyperspy\_components\expression.py", line 289, in compile_function
    self._f = sympy.utilities.lambdify(variables + parameters, eval_expr,
  File "C:\Users\yd2.lee\AppData\Local\Miniforge3\lib\site-packages\sympy\utilities\lambdify.py", line 781, in lambdify
    buf = _get_namespace(m)
  File "C:\Users\yd2.lee\AppData\Local\Miniforge3\lib\site-packages\sympy\utilities\lambdify.py", line 926, in _get_namespace
    _import(m)
  File "C:\Users\yd2.lee\AppData\Local\Miniforge3\lib\site-packages\sympy\utilities\lambdify.py", line 158, in _import
    raise ImportError(
ImportError: Cannot import 'None' with 'import_module('numexpr')' command
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In [5], line 1
----> 1 s.remove_background()

File ~\AppData\Local\Miniforge3\lib\site-packages\hyperspy\_signals\signal1d.py:1267, in Signal1D.remove_background(self, signal_range, background_type, polynomial_order, fast, zero_fill, plot_remainder, show_progressbar, return_model, display, toolkit)
   1265 model = Model1D(self)
   1266 if signal_range == 'interactive':
-> 1267     br = BackgroundRemoval(self, background_type=background_type,
   1268                            polynomial_order=polynomial_order,
   1269                            fast=fast,
   1270                            plot_remainder=plot_remainder,
   1271                            show_progressbar=show_progressbar,
   1272                            zero_fill=zero_fill,
   1273                            model=model)
   1274     gui_dict = br.gui(display=display, toolkit=toolkit)
   1275     if return_model:

File ~\AppData\Local\Miniforge3\lib\site-packages\hyperspy\signal_tools.py:1478, in BackgroundRemoval.__init__(self, signal, background_type, polynomial_order, fast, plot_remainder, zero_fill, show_progressbar, model)
   1476 self.zero_fill = zero_fill
   1477 self.show_progressbar = show_progressbar
-> 1478 self.set_background_estimator()

File ~\AppData\Local\Miniforge3\lib\site-packages\hyperspy\signal_tools.py:1495, in BackgroundRemoval.set_background_estimator(self)
   1493     for component in self.model:
   1494         self.model.remove(component)
-> 1495 self.background_estimator, self.bg_line_range = _get_background_estimator(
   1496     self.background_type, self.polynomial_order)
   1497 if self.model is not None and len(self.model) == 0:
   1498     self.model.append(self.background_estimator)

File ~\AppData\Local\Miniforge3\lib\site-packages\hyperspy\signal_tools.py:1677, in _get_background_estimator(background_type, polynomial_order)
   1675     bg_line_range = 'full'
   1676 elif background_type == 'powerlaw':
-> 1677     background_estimator = components1d.PowerLaw()
   1678     bg_line_range = 'from_left_range'
   1679 elif background_type == 'exponential':

File ~\AppData\Local\Miniforge3\lib\site-packages\hyperspy\_components\power_law.py:67, in PowerLaw.__init__(self, A, r, origin, left_cutoff, module, compute_gradients, **kwargs)
     65 def __init__(self, A=10e5, r=3., origin=0., left_cutoff=0.0,
     66              module="numexpr", compute_gradients=False, **kwargs):
---> 67     super().__init__(
     68         expression="where(left_cutoff<x, A*(-origin + x)**-r, 0)",
     69         name="PowerLaw",
     70         A=A,
     71         r=r,
     72         origin=origin,
     73         left_cutoff=left_cutoff,
     74         position="origin",
     75         module=module,
     76         autodoc=False,
     77         compute_gradients=compute_gradients,
     78         linear_parameter_list=['A'],
     79         check_parameter_linearity=False,
     80         **kwargs,
     81     )
     83     self.origin.free = False
     84     self.left_cutoff.free = False

File ~\AppData\Local\Miniforge3\lib\site-packages\hyperspy\_components\expression.py:177, in Expression.__init__(self, expression, name, position, module, autodoc, add_rotation, rotation_center, rename_pars, compute_gradients, linear_parameter_list, check_parameter_linearity, **kwargs)
    174 self._compute_gradients = compute_gradients
    176 if rotation_center is None:
--> 177     self.compile_function(module=module, position=position)
    178 else:
    179     self.compile_function(module=module, position=rotation_center)

File ~\AppData\Local\Miniforge3\lib\site-packages\hyperspy\_components\expression.py:289, in Expression.compile_function(self, module, position)
    287 # Create compiled function
    288 variables = [x, y] if self._is2D else [x]
--> 289 self._f = sympy.utilities.lambdify(variables + parameters, eval_expr,
    290                    modules=module, dummify=False)
    292 if self._is2D:
    293     def f(x, y): return self._f(
    294         x, y, *[p.value for p in self.parameters])

File ~\AppData\Local\Miniforge3\lib\site-packages\sympy\utilities\lambdify.py:781, in lambdify(args, expr, modules, printer, use_imps, dummify, cse)
    779 namespace = {} # type: tDict[str, Any]
    780 for m in namespaces[::-1]:
--> 781     buf = _get_namespace(m)
    782     namespace.update(buf)
    784 if hasattr(expr, "atoms"):
    785     #Try if you can extract symbols from the expression.
    786     #Move on if expr.atoms in not implemented.

File ~\AppData\Local\Miniforge3\lib\site-packages\sympy\utilities\lambdify.py:926, in _get_namespace(m)
    922 """
    923 This is used by _lambdify to parse its arguments.
    924 """
    925 if isinstance(m, str):
--> 926     _import(m)
    927     return MODULES[m][0]
    928 elif isinstance(m, dict):

File ~\AppData\Local\Miniforge3\lib\site-packages\sympy\utilities\lambdify.py:158, in _import(module, reload)
    155         except ImportError:
    156             pass
--> 158     raise ImportError(
    159         "Cannot import '%s' with '%s' command" % (module, import_command))
    161 # Add translated names to namespace
    162 for sympyname, translation in translations.items():

ImportError: Cannot import 'None' with 'import_module('numexpr')' command

#### Python environement:
 - HyperSpy version: 1.7.3
 - Python version: 3.10

Thank you in advance.

**Comment by ydlee1227** [comment]
I found gitter log concerning this error. It has been solved by installing numexpr. So I tried but it doesn't work.

**Comment by ydlee1227** [comment]
It happend at demo, EELS_analysis.ipynb.

**Comment by ydlee1227** [comment]
I tried in new conda env, it works well with pip install hyperspy well. It seems that the pypi and conda-forge has a conflict.
