### ISSUE TITLE
Unable to load bcf file

### ISSUE THREAD

**Issue by MinhTamHoang** [hyperspy/hyperspy#3132]
Hello,

I am trying to load bruker bcf file, but I got errors as attached below:

ERROR:hyperspy.io:If this file format is supported, please report this error to the HyperSpy developers.
Traceback (most recent call last):
  File "EBSD_analysis.py", line 4, in <module>
    file = hs.load("APMT_200x_EBSD_2x4_indent_single_indent_top4.bcf")
  File "/anaconda3/lib/python3.7/site-packages/hyperspy/io.py", line 467, in load
    for filename in filenames]
  File "/anaconda3/lib/python3.7/site-packages/hyperspy/io.py", line 467, in <listcomp>
    for filename in filenames]
  File "/anaconda3/lib/python3.7/site-packages/hyperspy/io.py", line 525, in load_single_file
    return load_with_reader(filename=filename, reader=reader, **kwds)
  File "/anaconda3/lib/python3.7/site-packages/hyperspy/io.py", line 545, in load_with_reader
    file_data_list = reader.file_reader(filename, **kwds)
  File "/anaconda3/lib/python3.7/site-packages/hyperspy/io_plugins/bruker.py", line 1247, in file_reader
    return bcf_reader(filename, *args, **kwds)
  File "/anaconda3/lib/python3.7/site-packages/hyperspy/io_plugins/bruker.py", line 1281, in bcf_reader
    obj_bcf = BCF_reader(filename, instrument=instrument)
  File "/anaconda3/lib/python3.7/site-packages/hyperspy/io_plugins/bruker.py", line 913, in __init__
    header_file = self.get_file('EDSDatabase/HeaderData')
  File "/anaconda3/lib/python3.7/site-packages/hyperspy/io_plugins/bruker.py", line 451, in get_file
    item = item[i]
KeyError: 'EDSDatabase'

How can I resolve  these errors?

Thanks,

**Comment by hakonanes** [comment]
Hi @freshcrystal,

HyperSpy cannot ready EBSD patterns from Brukers BCF files. Nor can kikuchipy, extending HS for EBSD analysis. We can however read Bruker's HDF5 EBSD format. I've read about a BCF->HDF5 converter script provided by Bruker, can you use this?

**Comment by freshcrystal** [comment]
Thanks for your response. Can you tell where I can find the conversion script? Thanks.

**Comment by hakonanes** [comment]
I do not, unfortunately.
