### ISSUE TITLE
traits, again

### ISSUE THREAD

**Issue by sem-geologist** [hyperspy/hyperspy#3470]
#### Describe the bug
```python
>>> import hyperspy.api as hs
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import hyperspy.api as hs
  File "/media/zircon/bulk-data/mamboforge/envs/rsciio-dev/lib/python3.13/site-packages/hyperspy/api.py", line 23, in <module>
    from hyperspy.defaults_parser import preferences
  File "/media/zircon/bulk-data/mamboforge/envs/rsciio-dev/lib/python3.13/site-packages/hyperspy/defaults_parser.py", line 25, in <module>
    import traits.api as t
  File "/media/zircon/bulk-data/mamboforge/envs/rsciio-dev/lib/python3.13/site-packages/traits/api.py", line 17, in <module>
    from .constants import (
    ...<7 lines>...
    )
  File "/media/zircon/bulk-data/mamboforge/envs/rsciio-dev/lib/python3.13/site-packages/traits/constants.py", line 13, in <module>
    import traits.ctraits
ImportError: /media/zircon/bulk-data/mamboforge/envs/rsciio-dev/lib/python3.13/site-packages/traits/ctraits.cpython-313-x86_64-linux-gnu.so: undefined symbol: Py_TRASHCAN_SAFE_BEGIN

```

#### To Reproduce
```
import hyperspy.api as hs
```

#### Expected behavior
hyperspy should just work with minimal installation.

#### Python environment:
 - HyperSpy version: 2.2 (installed through pip, as mamba would not do it)
 - Python version: 3.13 (install through mamba)

#### Additional context
Traits was causing problems from I don't know how long - it is one of biggest installation pains.
No, I dont want to get whole bundle or any graphical clutter, I just want to see that modified metadata structure in `rsciio` development version works ok with hyperspy and exspy. Documentation (again) lies that `pip install hyperspy` installs only minimal version. I practically see matplotlib, traits and other bloated garbage being pulled in, thus nope.

**Comment by francisco-dlp** [comment]
Thanks for reporting the issue. The problem is that the current version of traits doesn't support Python 3.13, see the following comment https://github.com/hyperspy/hyperspy/pull/3468#discussion_r1865652650

As for the minimal hyperspy installation installing traits, the reason is that a number of essential HyperSpy objects rely on traits. `traits` could be replaced by the pure python `traitlets`, but that would make supporting multiple UIs harder. I agree that it would be nice to split hyperspy's matplotlib plotting features into a separate package.

**Comment by sem-geologist** [comment]
Seems that the only workaround is to downgrade the environment to python 3.12 and reinstall hyperspy and exspy...

**Comment by jlaehne** [comment]
The relevant fix to traits has been merged and released last week: https://github.com/enthought/traits/issues/1815 

#3468 is explicitly adding python 3.13 support to hyperspy
