### ISSUE TITLE
BUG: trait / type errors when iterating in spikes_removal_tool

### ISSUE THREAD

**Issue by to266** [hyperspy/hyperspy#527]
With a particular type of files (I haven't found what's so peculiar about them and managed to reproduce with a synthetic example yet) `spikes_removal_tool` (the GUI version) outputs one exception per iteration (i.e. per navigation pixel):

```python
ERROR:traits:Exception occurred in traits notification handler for object: y axis, trait: index, old value: 49, new value: 0
Traceback (most recent call last):
  File "/home/to266/anaconda/lib/python2.7/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/home/to266/anaconda/lib/python2.7/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/home/to266/hyperspy/hyperspy/drawing/spectrum.py", line 146, in update
    line.update()
  File "/home/to266/hyperspy/hyperspy/drawing/spectrum.py", line 312, in update
    ydata = self.data_function(axes_manager=self.axes_manager).real
  File "/home/to266/hyperspy/hyperspy/gui/egerton_quantification.py", line 407, in get_interpolated_spectrum
    left, right = self.get_interpolation_range()
  File "/home/to266/hyperspy/hyperspy/gui/egerton_quantification.py", line 391, in get_interpolation_range
    left = self.argmax - self.default_spike_width
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

Strangely the function actually does its job, the only problem is then the actual error reports, that (if run in a notebook) just jam the pipeline and crashe both the browser (chromium / firefox in my case) and the ipython kernel. It takes only about 30seconds when run in a qtconsole (as the output just scrolls and is probably stored differently than the notebook), so for now I use that.

**Comment by vidartf** [comment]
The two PRs that together were hoped to fix this have been merged. Is this still an issue?

**Comment by francisco-dlp** [comment]
AFAIK yes, thanks for spotting it.
