### ISSUE TITLE
`Signal._get_navigation_signal` broken for single images

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#538]
The following raises an exception:

```python

>>> import hyperspy.hspy as hs
>>> im = hs.signals.Image(np.emp
np.empty       np.empty_like  
>>> im = hs.signals.Image(np.empty((2, 2)))
>>> im._get
im._get_factors              im._get_navigation_signal    
im._get_loadings             im._get_undefined_axes_list  
>>> im._get_navigation_signal()
Traceback (most recent call last):
  File "<ipython-input-4-483f64819823>", line 1, in <module>
    im._get_navigation_signal()
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 4324, in _get_navigation_signal
    return self.__class__(np.array([0, ]).astype(self.data.dtype))
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/image.py", line 31, in __init__
    self.axes_manager.set_signal_dimension(2)
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 702, in set_signal_dimension
    " than the number of axes which is %i" % len(self._axes))
ValueError: The signal dimension cannot be greater than the number of axes which is 1

```

**Comment by francisco-dlp** [comment]
Fixed in #540
