### ISSUE TITLE
Using hyperspy on EELS DB webserver

### ISSUE THREAD

**Issue by ewels** [hyperspy/hyperspy#717]
Hi all,

In #475 we briefly discussed [using hyperspy](https://github.com/hyperspy/hyperspy/issues/475#issuecomment-77152343) to parse data formats. At the time I had a quick go at getting hyperspy running on the webserver and didn't have much luck.

The idea has been floating around in the back of my mind though, and this morning I had another shot. After quite a bit of fiddling, I finally managed to get miniconda to work. With miniconda, I _sort of_ got hyperspy working:

```
[~]# hyperspy -h
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 30 days
/home/eelsdb/miniconda/lib/python2.7/site-packages/hyperspy/io_plugins/tiff.py:31: UserWarning: Failed to import the optional scikit image package. Loading of some compressed images will be slow.

  "Failed to import the optional scikit image package. "

The Image (PIL) IO features are not available
/home/eelsdb/miniconda/lib/python2.7/site-packages/IPython/utils/path.py:258: UserWarning: get_ipython_dir has moved to the IPython.paths module
  warn("get_ipython_dir has moved to the IPython.paths module")
usage: hyperspy [-h] [-v] [--overwrite_profile]
                [--ipython_args [IPYTHON_ARGS [IPYTHON_ARGS ...]]]
                [{terminal,console,qtconsole,notebook}]

Multidimensional data analysis toolbox

positional arguments:
  {terminal,console,qtconsole,notebook}
                        Selects the IPython environment in which to start
                        Hyperspy. The default is terminal

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit
  --overwrite_profile   Overwrite the Ipython profile with the default one.
  --ipython_args [IPYTHON_ARGS [IPYTHON_ARGS ...]]
                        Arguments to be passed to IPython. This option must be
                        the last one.Look at the IPython documentation for
                        available options.
```

This looks good! Except for the bit about the mkl trial mode expiring in 30 days. I tried getting rid of mkl (`conda remove mkl`), but then hyperspy wouldn't run:

```
[~]# hyperspy -h
Traceback (most recent call last):
  File "/home/eelsdb/miniconda/bin/hyperspy", line 40, in <module>
    import hyperspy.defaults_parser
  File "/home/eelsdb/miniconda/lib/python2.7/site-packages/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/eelsdb/miniconda/lib/python2.7/site-packages/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/eelsdb/miniconda/lib/python2.7/site-packages/hyperspy/io_plugins/msa.py", line 26, in <module>
    import numpy as np
  File "/home/eelsdb/miniconda/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/home/eelsdb/miniconda/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/eelsdb/miniconda/lib/python2.7/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/home/eelsdb/miniconda/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/home/eelsdb/miniconda/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/home/eelsdb/miniconda/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory
```

I quite like the idea of being able to use hyperspy for the EELS DB website in the future. Any ideas on how I can get it running for more than 30 days?

Cheers,

Phil

**Comment by ewels** [comment]
ps. Currently, I only foresee using hyperspy for file format conversions. I don't think that the current server setup has the power to do anything more complicated. Hyperspy will always be better / more up to date with spectra file formats, so if it can handle spectra submissions and convert to a common format (eg. JSON), that would be super handy.

**Comment by to266** [comment]
Hi,

This might help:
http://stackoverflow.com/a/25367233

I'd also try to reinstall numpy (as it's the bit that complains)

**Comment by francisco-dlp** [comment]
We use miniconda to run HyperSpy in travis. Our [travis config file](https://github.com/hyperspy/hyperspy/blob/master/.travis.yml) could be of help.

**Comment by ewels** [comment]
Thanks both - I think that the short answer is that if I want to do proper integration with HyperSpy, I need to move the website to a different (more expensive) web host.
