### ISSUE TITLE
Another traits/qt backend problem

### ISSUE THREAD

**Issue by jat255** [hyperspy/hyperspy#876]
Cannot import hyperspy api with latest master. This is on my Arch Linux install, and seems to be related once again to traits and it's import of pyqt4. From what I can tell, it looks like Jupyter is importing the Qt stuff using qt5, but since traits doesn't support qt5, when it goes to import the qt4 versions, there's a conflict. I'm not sure if this is a hyperspy problem, other than the dependency on traits. I'll look around some more to make sure this isn't just a problem with my environment...

``` bash
 $ ~/git_repos/hyperspy: git status                                                                                                                                                                                          
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

$ ~/git_repos/hyperspy: jupyter-qtconsole-py2 --version
4.1.1

$ ~/git_repos/hyperspy: pip2 list | grep -E "traits|pyface"
pyface (5.0.0)
traits (4.5.0)
traitsui (5.0.0)


$ ~/git_repos/hyperspy: pacman -Q | grep pyqt
pyqt4-common 4.11.4-4
pyqt5-common 5.5.1-2
python-pyqt4 4.11.4-4
python-pyqt5 5.5.1-2
python2-pyqt4 4.11.4-4
python2-pyqt5 5.5.1-2
```

``` python
In [1]: import hyperspy

In [2]: print(hyperspy.__version__)
0.9+dev

In [3]: import hyperspy.api as hs
Exception occurred in traits notification handler for object: <hyperspy.defaults_parser.GeneralConfig object at 0x7f236695fa70>, trait: logger_on, old value: False, new value: True
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "hyperspy/defaults_parser.py", line 123, in _logger_on_changed
    turn_logging_on()
  File "hyperspy/misc/ipython_tools.py", line 85, in turn_logging_on
    "# ============================\n")
  File "/usr/lib/python2.7/site-packages/IPython/core/logger.py", line 199, in log_write
    write(data)
TypeError: must be unicode, not str
ERROR:traits:Exception occurred in traits notification handler for object: <hyperspy.defaults_parser.GeneralConfig object at 0x7f236695fa70>, trait: logger_on, old value: False, new value: True
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "hyperspy/defaults_parser.py", line 123, in _logger_on_changed
    turn_logging_on()
  File "hyperspy/misc/ipython_tools.py", line 85, in turn_logging_on
    "# ============================\n")
  File "/usr/lib/python2.7/site-packages/IPython/core/logger.py", line 199, in log_write
    write(data)
TypeError: must be unicode, not str
Exception occurred in traits notification handler.
Please check the log file for details.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-5e09b9d2af1c> in <module>()
----> 1 import hyperspy.api as hs

/home/josh/git_repos/hyperspy/hyperspy/api.py in <module>()
     61 
     62 from hyperspy.Release import version as __version__
---> 63 from hyperspy import signals
     64 from hyperspy.io import load
     65 from hyperspy.defaults_parser import preferences

/home/josh/git_repos/hyperspy/hyperspy/signals.py in <module>()
     37 # -*- coding: utf-8 -*-
     38 
---> 39 from hyperspy._signals.spectrum import Spectrum
     40 from hyperspy._signals.image import Image
     41 from hyperspy._signals.eels import EELSSpectrum

/home/josh/git_repos/hyperspy/hyperspy/_signals/spectrum.py in <module>()
     23 
     24 from hyperspy.exceptions import DataDimensionError
---> 25 from hyperspy.signal import Signal
     26 from hyperspy.gui.egerton_quantification import SpikesRemoval
     27 

/home/josh/git_repos/hyperspy/hyperspy/signal.py in <module>()
     44 from hyperspy.axes import AxesManager
     45 from hyperspy import io
---> 46 from hyperspy.drawing import mpl_hie, mpl_hse, mpl_he
     47 from hyperspy.learn.mva import MVA, LearningResults
     48 import hyperspy.misc.utils

/home/josh/git_repos/hyperspy/hyperspy/drawing/mpl_hie.py in <module>()
     17 # along with  HyperSpy.  If not, see <http://www.gnu.org/licenses/>.
     18 
---> 19 from hyperspy.drawing import image, utils
     20 from hyperspy.drawing.mpl_he import MPL_HyperExplorer
     21 

/home/josh/git_repos/hyperspy/hyperspy/drawing/image.py in <module>()
     28 from hyperspy.drawing import widgets
     29 from hyperspy.drawing import utils
---> 30 from hyperspy.gui.tools import ImageContrastEditor
     31 from hyperspy.misc import math_tools
     32 from hyperspy.misc import rgb_tools

/home/josh/git_repos/hyperspy/hyperspy/gui/tools.py in <module>()
     21 import matplotlib.pyplot as plt
     22 import traits.api as t
---> 23 import traitsui.api as tu
     24 from traitsui.menu import (OKButton, CancelButton, OKCancelButtons)
     25 

/usr/lib/python2.7/site-packages/traitsui/api.py in <module>()
     34 
     35 try:
---> 36     from .editors.api import ArrayEditor
     37 except ImportError:
     38     # ArrayEditor depends on numpy, so ignore if numpy is not present.

/usr/lib/python2.7/site-packages/traitsui/editors/__init__.py in <module>()
     21 
     22 try:
---> 23     from .api import ArrayEditor
     24 except ImportError:
     25     pass

/usr/lib/python2.7/site-packages/traitsui/editors/api.py in <module>()
     22 from .button_editor import ButtonEditor
     23 from .check_list_editor import CheckListEditor
---> 24 from .code_editor import CodeEditor
     25 from .color_editor import ColorEditor
     26 from .compound_editor import CompoundEditor

/usr/lib/python2.7/site-packages/traitsui/editors/code_editor.py in <module>()
     34 #-------------------------------------------------------------------------------
     35 
---> 36 class ToolkitEditorFactory ( EditorFactory ):
     37     """ Editor factory for code editors.
     38     """

/usr/lib/python2.7/site-packages/traitsui/editors/code_editor.py in ToolkitEditorFactory()
     46 
     47     # Background color for marking lines
---> 48     mark_color = Color( 0xECE9D8 )
     49 
     50     # Object trait containing the currently selected line (optional)

/usr/lib/python2.7/site-packages/traits/traits.pyc in __call__(self, *args, **metadata)
    487 
    488     def __call__ ( self, *args, **metadata ):
--> 489         return self.maker_function( *args, **metadata )
    490 
    491 class TraitImportError ( TraitFactory ):

/usr/lib/python2.7/site-packages/traits/traits.pyc in Color(*args, **metadata)
   1201     from traitsui.toolkit_traits import ColorTrait
   1202 
-> 1203     return ColorTrait( *args, **metadata )
   1204 
   1205 Color = TraitFactory( Color )

/usr/lib/python2.7/site-packages/traitsui/toolkit_traits.pyc in ColorTrait(*args, **traits)
      5 
      6 def ColorTrait ( *args, **traits ):
----> 7     return toolkit().color_trait( *args, **traits )
      8 
      9 def RGBColorTrait ( *args, **traits ):

/usr/lib/python2.7/site-packages/traitsui/toolkit.pyc in toolkit(*toolkits)
    110     if ETSConfig.toolkit:
    111         # If a toolkit has already been set for ETSConfig, then use it:
--> 112         _toolkit = _import_toolkit(ETSConfig.toolkit)
    113         return _toolkit
    114     else:

/usr/lib/python2.7/site-packages/traitsui/toolkit.pyc in _import_toolkit(name)
     52         import wxversion
     53         wxversion.select("2.8")
---> 54     return __import__( name, globals=globals(), level=1 ).toolkit
     55 
     56 

/usr/lib/python2.7/site-packages/traitsui/qt4/__init__.py in <module>()
     22 #----------------------------------------------------------------------------
     23 
---> 24 import toolkit
     25 
     26 # Reference to the GUIToolkit object for PyQt.

/usr/lib/python2.7/site-packages/traitsui/qt4/toolkit.py in <module>()
     22 assert_toolkit_import('qt4')
     23 
---> 24 from pyface.qt import QtCore, QtGui, qt_api
     25 
     26 if qt_api == 'pyqt':

/usr/lib/python2.7/site-packages/pyface/qt/QtCore.py in <module>()
      2 
      3 if qt_api == 'pyqt':
----> 4     from PyQt4.QtCore import *
      5 
      6     from PyQt4.QtCore import pyqtProperty as Property

RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class
```

**Comment by jat255** [comment]
Another datapoint: I don't have this problem on my Windows installation (with the latest master, same pyface, traits, and traitsui versions), which does not have PyQt5 installed.

**Comment by jat255** [comment]
More data:

If I uninstall the `python2-pyqt5` package, I get a different error:

```python
import hyperspy.api as hs
set APIs

Logging is active
The log is stored in the hyperspy_log.py file in the current directory
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-5e09b9d2af1c> in <module>()
----> 1 import hyperspy.api as hs

/home/josh/git_repos/hyperspy/hyperspy/api.py in <module>()
     61 
     62 from hyperspy.Release import version as __version__
---> 63 from hyperspy import signals
     64 from hyperspy.io import load
     65 from hyperspy.defaults_parser import preferences

/home/josh/git_repos/hyperspy/hyperspy/signals.py in <module>()
     37 # -*- coding: utf-8 -*-
     38 
---> 39 from hyperspy._signals.spectrum import Spectrum
     40 from hyperspy._signals.image import Image
     41 from hyperspy._signals.eels import EELSSpectrum

/home/josh/git_repos/hyperspy/hyperspy/_signals/spectrum.py in <module>()
     23 
     24 from hyperspy.exceptions import DataDimensionError
---> 25 from hyperspy.signal import Signal
     26 from hyperspy.gui.egerton_quantification import SpikesRemoval
     27 

/home/josh/git_repos/hyperspy/hyperspy/signal.py in <module>()
     44 from hyperspy.axes import AxesManager
     45 from hyperspy import io
---> 46 from hyperspy.drawing import mpl_hie, mpl_hse, mpl_he
     47 from hyperspy.learn.mva import MVA, LearningResults
     48 import hyperspy.misc.utils

/home/josh/git_repos/hyperspy/hyperspy/drawing/mpl_hie.py in <module>()
     17 # along with  HyperSpy.  If not, see <http://www.gnu.org/licenses/>.
     18 
---> 19 from hyperspy.drawing import image, utils
     20 from hyperspy.drawing.mpl_he import MPL_HyperExplorer
     21 

/home/josh/git_repos/hyperspy/hyperspy/drawing/image.py in <module>()
     28 from hyperspy.drawing import widgets
     29 from hyperspy.drawing import utils
---> 30 from hyperspy.gui.tools import ImageContrastEditor
     31 from hyperspy.misc import math_tools
     32 from hyperspy.misc import rgb_tools

/home/josh/git_repos/hyperspy/hyperspy/gui/tools.py in <module>()
     21 import matplotlib.pyplot as plt
     22 import traits.api as t
---> 23 import traitsui.api as tu
     24 from traitsui.menu import (OKButton, CancelButton, OKCancelButtons)
     25 

/usr/lib/python2.7/site-packages/traitsui/api.py in <module>()
     34 
     35 try:
---> 36     from .editors.api import ArrayEditor
     37 except ImportError:
     38     # ArrayEditor depends on numpy, so ignore if numpy is not present.

/usr/lib/python2.7/site-packages/traitsui/editors/__init__.py in <module>()
     21 
     22 try:
---> 23     from .api import ArrayEditor
     24 except ImportError:
     25     pass

/usr/lib/python2.7/site-packages/traitsui/editors/api.py in <module>()
     22 from .button_editor import ButtonEditor
     23 from .check_list_editor import CheckListEditor
---> 24 from .code_editor import CodeEditor
     25 from .color_editor import ColorEditor
     26 from .compound_editor import CompoundEditor

/usr/lib/python2.7/site-packages/traitsui/editors/code_editor.py in <module>()
     34 #-------------------------------------------------------------------------------
     35 
---> 36 class ToolkitEditorFactory ( EditorFactory ):
     37     """ Editor factory for code editors.
     38     """

/usr/lib/python2.7/site-packages/traitsui/editors/code_editor.py in ToolkitEditorFactory()
     46 
     47     # Background color for marking lines
---> 48     mark_color = Color( 0xECE9D8 )
     49 
     50     # Object trait containing the currently selected line (optional)

/usr/lib/python2.7/site-packages/traits/traits.pyc in __call__(self, *args, **metadata)
    487 
    488     def __call__ ( self, *args, **metadata ):
--> 489         return self.maker_function( *args, **metadata )
    490 
    491 class TraitImportError ( TraitFactory ):

/usr/lib/python2.7/site-packages/traits/traits.pyc in Color(*args, **metadata)
   1201     from traitsui.toolkit_traits import ColorTrait
   1202 
-> 1203     return ColorTrait( *args, **metadata )
   1204 
   1205 Color = TraitFactory( Color )

/usr/lib/python2.7/site-packages/traitsui/toolkit_traits.pyc in ColorTrait(*args, **traits)
      5 
      6 def ColorTrait ( *args, **traits ):
----> 7     return toolkit().color_trait( *args, **traits )
      8 
      9 def RGBColorTrait ( *args, **traits ):

/usr/lib/python2.7/site-packages/traitsui/toolkit.pyc in toolkit(*toolkits)
    107     if ETSConfig.toolkit:
    108         # If a toolkit has already been set for ETSConfig, then use it:
--> 109         _toolkit = _import_toolkit(ETSConfig.toolkit)
    110         return _toolkit
    111     else:

/usr/lib/python2.7/site-packages/traitsui/toolkit.pyc in _import_toolkit(name)
     49 
     50 def _import_toolkit ( name ):
---> 51     return __import__( name, globals=globals(), level=1 ).toolkit
     52 
     53 

/usr/lib/python2.7/site-packages/traitsui/qt4/__init__.py in <module>()
     16 # import pyface.qt before anything else is done so the sipapi
     17 # can be set correctly if needed
---> 18 import pyface.qt
     19 
     20 #----------------------------------------------------------------------------

/usr/lib/python2.7/site-packages/pyface/qt/__init__.py in <module>()
     38 
     39 elif qt_api == 'pyqt':
---> 40     prepare_pyqt4()
     41 
     42 elif qt_api != 'pyside':

/usr/lib/python2.7/site-packages/pyface/qt/__init__.py in prepare_pyqt4()
     17     sip.setapi('QDate', 2)
     18     sip.setapi('QDateTime', 2)
---> 19     sip.setapi('QString', 2)
     20     sip.setapi('QTextStream', 2)
     21     sip.setapi('QTime', 2)

ValueError: API 'QString' has already been set to version 1
```


If I set the `'QString'` API to 2 in `hyperspy.__init__`, everything imports as normal.

**Comment by dnjohnstone** [comment]
Thanks for this @jat255 - I had an e-mail from @k8macarthur having a similar looking problem (although on Mac) yesterday... Error message as below.

`---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-7-f2b1632a7741> in <module>()
      1 #Opens a load window. Use hs.load('filename') if filename is known specifically.
      2 
----> 3 s = hs.load()
      4 s.set_signal_type('EDS_TEM')
      5 s.metadata.General.title = 'Original Data Cube'

/Users/macark/anaconda/lib/python2.7/site-packages/hyperspy/io.pyc in load(filenames, record_by, signal_type, signal_origin, stack, stack_axis, new_axis_name, mmap, mmap_dir, **kwds)
    159             from hyperspy.gui.tools import Load
    160             load_ui = Load()
--> 161             load_ui.edit_traits()
    162             if load_ui.filename:
    163                 filenames = load_ui.filename

/Users/macark/anaconda/lib/python2.7/site-packages/traits-4.5.0-py2.7-macosx-10.5-x86_64.egg/traits/has_traits.pyc in edit_traits(self, view, parent, kind, context, handler, id, scrollable, **args)
   1857 
   1858         return view.ui( context, parent, kind, self.trait_view_elements(),
-> 1859                         handler, id, scrollable, args )
   1860 
   1861     #---------------------------------------------------------------------------

/Users/macark/anaconda/lib/python2.7/site-packages/traitsui-5.0.0-py2.7.egg/traitsui/view.pyc in ui(self, context, parent, kind, view_elements, handler, id, scrollable, args)
    431             kind = self.kind
    432 
--> 433         ui.ui( parent, kind )
    434 
    435         return ui

/Users/macark/anaconda/lib/python2.7/site-packages/traitsui-5.0.0-py2.7.egg/traitsui/ui.pyc in ui(self, parent, kind)
    219                                    dispatch = 'ui' )
    220         self.rebuild = getattr( toolkit(), 'ui_' + kind )
--> 221         self.rebuild( self, parent )
    222 
    223     #---------------------------------------------------------------------------

/Users/macark/anaconda/lib/python2.7/site-packages/traitsui-5.0.0-py2.7.egg/traitsui/toolkit.pyc in ui_livemodal(self, ui, parent)
    171             interface using information from the specified UI object.
    172         """
--> 173         raise NotImplementedError
    174 
    175     def ui_live ( self, ui, parent ):

NotImplementedError: `

**Comment by vidartf** [comment]
Consider using #877 to get some helpful debug output like this:
```python
from hyperspy.logger import set_log_level
set_log_level('DEBUG')
import hyperspy.api as hs
hs.load()  # Checks that traitsui backend is OK
```

**Comment by jat255** [comment]
Thanks, I'll give this a shot later today and let you know what I find.

**Comment by jat255** [comment]
Ok, so after testing, I ran the commands with debug output enabled as suggested by @vidartf.

In my base installation, I got the following output (in addition to the error from before):
```
DEBUG:hyperspy.gui:Loading hyperspy.gui
DEBUG:hyperspy.gui:Current MPL backend: Qt5Agg
DEBUG:hyperspy.gui:Current ETS toolkit: qt4
DEBUG:hyperspy.gui:Current ETS toolkit set to: qt4
```

So it appears that `matplotlib` is defaulting to Qt5, since I have that installed on my system.

In the virtualenv (which did work, even with Qt5 installed) I got the following result:
```
DEBUG:hyperspy.gui:Loading hyperspy.gui
DEBUG:hyperspy.gui:Current MPL backend: TkAgg
DEBUG:hyperspy.gui:Current ETS toolkit: qt4
DEBUG:hyperspy.gui:Current ETS toolkit set to: qt4
```
Meaning that for whatever reason, the default toolkit in that virtualenv is `TkAgg`, which prevents the conflict between Qt versions.

To fix the problem, I added the following line to `~/.config/matplotlib/matplotlibrc`:
```
backend      : qt4agg
```
Which let me load the hyperspy api in my base installation, and gave the following debug output:
```
DEBUG:hyperspy.gui:Loading hyperspy.gui
DEBUG:hyperspy.gui:Current MPL backend: Qt4Agg
DEBUG:hyperspy.gui:Current ETS toolkit: qt4
DEBUG:hyperspy.gui:Current ETS toolkit set to: qt4
```

I'm not sure if my installation is specific with this problem, but it does seem that we have to force the older version of Qt so ETS is happy. It may be worth adding something to the documentation about this, at least until traits catches up with Qt5 (see [here](https://github.com/enthought/traitsui/pull/241), although there'e been no progress on it since Oct. 2015). I suppose this might be one more reason to see if we can drop the traitsui dependency.

**Comment by k8macarthur** [comment]
What ever was rolled over the weekend #281 I think? Seemed to fix my install problem. Hyperspy seems to work fine from my Mac now.

**Comment by jat255** [comment]
@vidartf good question! I'm not sure, actually. I've been using hyperspy just fine on my laptop, but I probably still have that `qt4agg` line in my matplotlib config. I don't have the machine with me, so I can't test. I don't think this is a Hyperspy problem, per se. More of an issue with upstream dependencies not playing nicely together.

**Comment by sem-geologist** [comment]
I want to confirm that problem is still here. (Debian testing with both PyQt4 and PyQt5 installed). everything works ok if I get rid of PyQt5. however on Debian testing I have to have both Qt's(KDE moved to Qt5, and some older programs uses still Qt4). In notebook it kind works ok, If %gui Qt4 is declared at the beggining. However the situation disallows using hyperspy from python console or py scripts. This all goes ti traitsui. and it fails while hyperspy trying to import it.
```python
>>> import hyperspy.api as hs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../development/git/hyperspy/hyperspy/api.py", line 72, in <module>
    from hyperspy import signals
  File "../development/git/hyperspy/hyperspy/signals.py", line 40, in <module>
    from hyperspy._signals.signal1d import Signal1D
  File "../development/git/hyperspy/hyperspy/_signals/signal1d.py", line 23, in <module>
    from hyperspy.signal import BaseSignal
  File "../development/git/hyperspy/hyperspy/signal.py", line 35, in <module>
    from hyperspy.drawing import mpl_hie, mpl_hse, mpl_he
  File "../development/git/hyperspy/hyperspy/drawing/mpl_hie.py", line 19, in <module>
    from hyperspy.drawing import image, utils
  File "../development/git/hyperspy/hyperspy/drawing/image.py", line 27, in <module>
    from hyperspy.gui.tools import ImageContrastEditor
  File "../development/git/hyperspy/hyperspy/gui/tools.py", line 25, in <module>
    import traitsui.api as tu
  File "/home/<user>/.local/lib/python3.5/site-packages/traitsui/api.py", line 36, in <module>
    from .editors.api import ArrayEditor
  File "/home/<user>/.local/lib/python3.5/site-packages/traitsui/editors/__init__.py", line 23, in <module>
    from .api import ArrayEditor
  File "/home/<user>/.local/lib/python3.5/site-packages/traitsui/editors/api.py", line 24, in <module>
    from .code_editor import CodeEditor
  File "/home/<user>/.local/lib/python3.5/site-packages/traitsui/editors/code_editor.py", line 36, in <module>
    class ToolkitEditorFactory ( EditorFactory ):
  File "/home/<user>/.local/lib/python3.5/site-packages/traitsui/editors/code_editor.py", line 48, in ToolkitEditorFactory
    mark_color = Color( 0xECE9D8 )
  File "/home/<user>/.local/lib/python3.5/site-packages/traits/traits.py", line 489, in __call__
    return self.maker_function( *args, **metadata )
  File "/home/<user>/.local/lib/python3.5/site-packages/traits/traits.py", line 1203, in Color
    return ColorTrait( *args, **metadata )
  File "/home/<user>/.local/lib/python3.5/site-packages/traitsui/toolkit_traits.py", line 7, in ColorTrait
    return toolkit().color_trait( *args, **traits )
  File "/home/<user>/.local/lib/python3.5/site-packages/traitsui/toolkit.py", line 152, in toolkit
    _toolkit = _import_toolkit(ETSConfig.toolkit)
  File "/home/<user>/.local/lib/python3.5/site-packages/traitsui/toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "/home/<user>/.local/lib/python3.5/site-packages/traitsui/qt4/__init__.py", line 24, in <module>
    from . import toolkit
  File "/home/<user>/.local/lib/python3.5/site-packages/traitsui/qt4/toolkit.py", line 24, in <module>
    from pyface.qt import QtCore, QtGui, qt_api
  File "/home/<user>/.local/lib/python3.5/site-packages/pyface/qt/QtCore.py", line 4, in <module>
    from PyQt4.QtCore import *
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class
```

**Comment by francisco-dlp** [comment]
Yes, this is a recurrent issue. As HyperSpy is just a data analysis package, it's a shame that it gets broken due to issues with UI libraries.

This is not exactly a HyperSpy bug (it's rather a traitsui one), but I'll tag is a such to give more visibility to the issue.

**Comment by sem-geologist** [comment]
maybe there could be few ways to import hyperspy: hyperspy.api, which would use the gui, and `hyperspy.something` which would load no guis?

**Comment by francisco-dlp** [comment]
What about lazyimporting traitsui and matplotlib instead? In this way you'll only face the issue when trying to use any feature that requires them.

**Comment by vidartf** [comment]
+1 for lazy import, but maybe with a possibility to manually trigger hyperspy ui dependency import?

**Comment by jat255** [comment]
going through some old issues... this has been solved at some point by something
