### ISSUE TITLE
nosetest3 TestOutArg.test_indexmax failing

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#916]
Running nosetest3 on the current master in Ubuntu 15.10, I get the following error: 
```python
======================================================================
ERROR: hyperspy.tests.signal.test_tools.TestOutArg.test_indexmax
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "hyperspy/dev/hyperspy/hyperspy/hyperspy/tests/signal/test_tools.py", line 491, in test_indexmax
    self._run_single(self.s.indexmax, self.s, dict(axis=0))
  File "hyperspy/dev/hyperspy/hyperspy/hyperspy/tests/signal/test_tools.py", line 444, in _run_single
    r = f(out=s1, **kwargs)
  File "hyperspy/dev/hyperspy/hyperspy/hyperspy/signal.py", line 4405, in indexmax
    out=out)
  File "hyperspy/dev/hyperspy/hyperspy/hyperspy/signal.py", line 4010, in _apply_function_on_data_and_remove_axis
    function(self.data, axis=ar_axes, out=out.data,)
TypeError: argmax() got an unexpected keyword argument 'out'
```

Which is a bit odd, since running `ndarray.argmax(out=...)` in an ipython3 terminal works fine.

**Comment by vidartf** [comment]
I've had this issue as well. It's related to the numpy version. Does `np.argmax(out=...)` work? If I remember correctly, this requires numpy version 1.10.

**Comment by magnunor** [comment]
You're right: doing ndarray.argmax(out=...) works, but np.argmax(an_array, out=...) does not.

To replicate:
```python
import numpy as np
a = np.array([0])
b = np.arange(10)
b.argmax(out=a) # Works fine
np.argmax(b, out=a) # Does not work
np.__version__ # output: '1.8.2'
```

**Comment by magnunor** [comment]
No longer a problem in the current Ubuntu version (16.04), due to it using a newer version of Numpy. Close this?

**Comment by francisco-dlp** [comment]
This is actually a bug that #910 fixes. Let's wait until #910 is merged.

**Comment by francisco-dlp** [comment]
#910
